import { test, expect } from '@playwright/test';

test('pratinjau desktop menampilkan model kurikulum tematik',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Selamat datang kembali'})).toBeVisible();
  await page.getByRole('button',{name:'Lihat pratinjau aplikasi'}).click();
  await expect(page.getByRole('heading',{name:'Perjalanan belajar'})).toBeVisible();
  await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
  await page.getByRole('button',{name:/Alya Putri Kupu-kupu/}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('spinbutton',{name:'Level awal Bahasa Indonesia (terkunci)'})).toBeDisabled();
  await expect(page.getByText('English Exposure',{exact:true}).first()).toBeVisible();
  await expect(page.getByText(/Karakter tidak diberi level/)).toBeVisible();
  await page.getByRole('button',{name:'Simpan profil siswa'}).click();
  await expect(page.getByRole('status')).toContainText('pratinjau');
  await page.getByRole('button',{name:'Tutup',exact:true}).click();
  await page.getByRole('navigation').getByRole('button',{name:/Data siswa/}).click();
  await expect(page.getByRole('heading',{name:'Sesi Pagi'})).toBeVisible();
  await expect(page.getByText(/08\.00–09\.30 · 90 menit/)).toBeVisible();
  await page.getByRole('searchbox',{name:'Cari siswa'}).fill('Bima');
  await expect(page.getByRole('button',{name:/Bima Pratama/})).toBeVisible();
  await expect(page.getByRole('button',{name:/Alya Putri/})).toHaveCount(0);
  await page.getByRole('searchbox',{name:'Cari siswa'}).fill('');
  await page.getByRole('button',{name:/Buat sesi jadwal/}).click();
  await page.getByLabel('Nama sesi').fill('Sesi Siang');
  await page.getByLabel('Jam mulai').fill('13:00');
  await page.getByLabel('Jam selesai').fill('14:15');
  await expect(page.locator('#schedule-duration')).toContainText('75 menit');
  await page.getByRole('button',{name:'Simpan sesi jadwal'}).click();
  await expect(page.getByRole('status')).toContainText('pratinjau');
  await page.getByRole('button',{name:'Tutup',exact:true}).click();
  await page.getByRole('button',{name:'Ruang kelas',exact:false}).first().click();
  await page.getByRole('button',{name:/Mulai sesi kelas/}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('combobox',{name:'Durasi kelas'})).toHaveValue('60');
  await page.getByRole('checkbox',{name:/Alya/}).check();
  await page.getByRole('button',{name:/Buka ruang kelas/}).click();
  await expect(page.getByRole('status')).toContainText('pratinjau');
  expect(errors).toEqual([]);
});

test('layar HP 390px tidak meluber dan formulir dapat digunakan',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  await page.getByRole('button',{name:'Lihat pratinjau aplikasi'}).click();
  await expect(page.getByRole('heading',{name:'Perjalanan belajar'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});
  await page.getByRole('navigation').getByRole('button',{name:/Data siswa/}).click();
  await page.getByRole('button',{name:/Tambah siswa/}).click();
  await expect(page.getByRole('textbox',{name:'Nama anak'})).toBeVisible();
  expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
  await page.getByRole('button',{name:'Tutup',exact:true}).click();
  await page.getByRole('button',{name:/Kembali ke login/}).click();
  await expect(page.getByRole('heading',{name:'Selamat datang kembali'})).toBeVisible();
});
