import { createClient } from '@supabase/supabase-js';
import { escapeHtml as h, progress, waLink, localDate } from './domain.js';
import './style.css';
import './curriculum.css';

const ORG_NAME='Rumah Belajar Rainbow Kids Alfatih';

const root = document.querySelector('#app');
let publicConfig = {};
try { const response = await fetch(new URL('./config.json', location.href)); if (response.ok) publicConfig = await response.json(); } catch { /* Local preview is available without configuration. */ }
const url = import.meta.env.VITE_SUPABASE_URL || publicConfig.supabaseUrl;
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || publicConfig.supabasePublishableKey;
const configured = url?.startsWith('https://') && key && !url.includes('PROJECT_REF');
const db = configured ? createClient(url,key) : null;
const state = { user:null, role:'teacher', name:'', view:'dashboard', students:[], classes:[], records:[], competencies:[], assessments:[], observations:[], alerts:[], members:[], assignments:[], profiles:[], themes:[], curriculum:[], active:null, demo:false, filter:'', onboarding:false };
let messageTimer;
const icons={dashboard:'◫',students:'◉',sessions:'▤',team:'♧',curriculum:'▥'};
const labels={dashboard:'Ringkasan',students:'Data siswa',sessions:'Ruang kelas',team:'Tim pengajar',curriculum:'Kurikulum'};
const subjects=['listening','speaking','reading','writing','math','ipas','english'];
const coreSubjects=['listening','speaking','reading','writing','math','ipas'];
const subjectLabels={listening:'Menyimak',speaking:'Berbicara',reading:'Membaca',writing:'Menulis',math:'Matematika',ipas:'IPAS',english:'English Exposure'};
const characterLabels={kemandirian:'Kemandirian',tanggung_jawab:'Tanggung jawab',kerja_sama:'Kerja sama',kepedulian:'Kepedulian',komunikasi_santun:'Komunikasi santun'};
const field=(label,name,type='text',value='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${h(value)}" ${extra}></label>`;
const select=(label,name,items,value='',extra='')=>`<label>${label}<select name="${name}" ${extra}>${items.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${h(v)}" ${v===value?'selected':''}>${h(t)}</option>`;}).join('')}</select></label>`;
const area=(label,name,value='',extra='')=>`<label>${label}<textarea name="${name}" rows="3" ${extra}>${h(value)}</textarea></label>`;
const empty=(title,text)=>`<div class="empty"><span>✧</span><h3>${title}</h3><p>${text}</p></div>`;
const studentFor=r=>state.students.find(s=>s.id===r.student_id);
const competenciesFor=id=>state.competencies.filter(c=>c.student_id===id);
const assessmentsFor=id=>state.assessments.filter(a=>a.session_student_id===id);
const observationFor=id=>state.observations.find(o=>o.session_student_id===id)||{english_rating:null,english_note:'',character_dimensions:[],character_note:''};
const activeCompetenciesFor=id=>competenciesFor(id).filter(c=>c.active!==false&&subjects.includes(c.subject));
const ready=s=>{const rows=activeCompetenciesFor(s.id).filter(c=>c.required);return rows.length?rows.every(c=>c.current_level>=c.target):s.reading_level>=s.reading_target&&s.math_level>=s.math_target;};
function notify(text,error=false){ document.querySelector('.toast')?.remove(); const el=document.createElement('div');el.className=`toast ${error?'error':''}`;el.role='status';el.textContent=text;document.body.append(el);clearTimeout(messageTimer);messageTimer=setTimeout(()=>el.remove(),6500); }
async function result(query){ const {data,error}=await query;if(error)throw new Error(error.message);return data; }
async function allRows(table,order='id') { const rows=[]; for(let from=0;;from+=500){let query=db.from(table).select('*').order(order);if(table==='assignments')query=query.order('teacher_id');if(table==='student_competencies'||table==='session_assessments')query=query.order('subject');const page=await result(query.range(from,from+499));rows.push(...page);if(page.length<500)return rows;} }
function guardDemo(){if(state.demo)throw new Error('Ini pratinjau. Hubungkan Supabase dan masuk untuk menyimpan data.');}
async function refresh(){
  if(state.demo){render();return;}
  const [students,classes,records,themes,curriculum,competencies,assessments,observations]=await Promise.all([
    allRows('students'),
    allRows('class_sessions'),
    allRows('session_students'),
    result(db.from('themes').select('*').order('name')),
    result(db.from('curriculum').select('*').order('level')),
    allRows('student_competencies','student_id'),
    allRows('session_assessments','session_student_id'),
    allRows('session_observations','session_student_id')
  ]);
  students.sort((a,b)=>a.name.localeCompare(b.name)); classes.sort((a,b)=>b.date.localeCompare(a.date)||b.created_at.localeCompare(a.created_at));
  Object.assign(state,{students,classes,records,themes,curriculum,competencies,assessments,observations});
  if(state.role==='owner'){
    [state.alerts,state.members,state.assignments,state.profiles]=await Promise.all([
      allRows('student_alerts','student_id'),allRows('access_list','email'),
      allRows('assignments','student_id'),allRows('profiles')
    ]);
  }
  render();
}
async function loadUser(user){
  state.user=user;state.demo=false;
  const profile=await result(db.from('profiles').select('*').eq('id',user.id).single());
  const member=await result(db.from('access_list').select('*').eq('email',profile.email).single());
  if(!member.active)throw new Error('Akses akun ini dinonaktifkan. Hubungi pemilik.');
  state.name=profile.name;state.role=member.role;state.onboarding=member.role==='teacher'&&localStorage.getItem('rb-onboarding-'+user.id)!=='1';await refresh();
}
function login(){
  root.innerHTML=`<main class="login"><section class="login-story"><div class="brand">b<span>·</span> ${ORG_NAME}</div><div><div class="eyebrow">RUANG TUMBUH BERSAMA</div><h1>Langkah kecil.<br><em>Kemajuan berarti.</em></h1><p>Lebih dekat dengan setiap anak.<br>Lebih tenang menjalani hari mengajar.</p><div class="story-card"><span class="sprout">✳</span><div><strong>Setiap anak punya jalannya.</strong><p>Materi personal · Evaluasi adaptif · Kabar baik untuk keluarga</p></div></div></div><small>Dibangun untuk guru yang peduli.</small></section><section class="login-form"><div class="login-box"><span class="pill">RUMAH BELAJAR / 02</span><h2>Selamat datang kembali</h2><p class="muted">Masuk untuk melanjutkan perjalanan belajar anak.</p>${!configured?'<div class="notice">Koneksi Supabase belum diatur. Pratinjau tampilan tersedia dengan data contoh.</div>':''}<form id="login-form">${field('Email terdaftar','email','email','','required autocomplete="email"')}${field('Kata sandi','password','password','','required minlength="8" autocomplete="current-password"')}<button class="primary full" ${configured?'':'disabled'}>Masuk ke ruang belajar →</button><button type="button" class="text-btn full" data-action="register" ${configured?'':'disabled'}>Aktivasi akun yang sudah didaftarkan pemilik</button></form><button class="secondary full" data-action="demo">Lihat pratinjau aplikasi</button><p class="fine">Akses hanya untuk pemilik dan guru terdaftar.</p></div></section></main>`;
}
function demo(){Object.assign(state,{demo:true,role:'teacher',name:'Guru Pratinjau',view:'dashboard',students:[
  {id:'demo-1',name:'Alya Putri',parent_name:'Bunda Rani',phone:'',interest:'Kupu-kupu & menggambar',reading_baseline:1,reading_level:4,reading_target:7,math_baseline:1,math_level:3,math_target:7,status:'Aktif',diagnostic:'Mengenali huruf vokal',learning_notes:'Senang belajar lewat gambar'},
  {id:'demo-2',name:'Bima Pratama',parent_name:'Ayah Danu',phone:'',interest:'Dinosaurus',reading_baseline:2,reading_level:3,reading_target:6,math_baseline:2,math_level:4,math_target:7,status:'Aktif'},
  {id:'demo-3',name:'Citra Kirana',parent_name:'Bunda Maya',phone:'',interest:'Cerita & hewan',reading_baseline:3,reading_level:7,reading_target:7,math_baseline:2,math_level:7,math_target:7,status:'Aktif'}
],classes:[],records:[],alerts:[],members:[],assignments:[],profiles:[],themes:[{name:'Pasar'},{name:'Alam & Lingkungan'}],curriculum:[]});state.competencies=state.students.flatMap(s=>subjects.map(subject=>({student_id:s.id,subject,baseline:subject==='math'?s.math_baseline:s.reading_baseline,current_level:subject==='math'?s.math_level:s.reading_level,target:subject==='math'?s.math_target:s.reading_target,evidence_count:subject==='writing'?1:0,repeat_count:0,intervention:false,required:subject!=='english',active:true})));state.assessments=[];state.observations=[];render();}
// Re-rendering replaces the whole page, so keep unsaved classroom inputs and the scroll position.
const drafts=new Map();let lastScreen='';
function saveDrafts(){document.querySelectorAll('.session-card form[data-id]').forEach(form=>{const values={};form.querySelectorAll('input,select,textarea').forEach(el=>{if(!el.name||el.disabled)return;if(el.type==='checkbox'){(values[el.name]??=[]);if(el.checked)values[el.name].push(el.value);}else values[el.name]=el.value;});drafts.set(form.dataset.form+':'+form.dataset.id,values);});}
function restoreDrafts(){document.querySelectorAll('.session-card form[data-id]').forEach(form=>{const values=drafts.get(form.dataset.form+':'+form.dataset.id);if(!values)return;form.querySelectorAll('input,select,textarea').forEach(el=>{if(!el.name||el.disabled||!(el.name in values))return;if(el.type==='checkbox')el.checked=values[el.name].includes(el.value);else el.value=values[el.name];});});}
function render(){
  if(!state.user&&!state.demo){login();return;}
  saveDrafts();const screen=state.view+':'+state.active;const y=screen===lastScreen?scrollY:0;lastScreen=screen;
  // Owners see aggregates and manage team/curriculum; classroom work belongs to teachers.
  if(state.role==='owner'&&state.view==='sessions'){state.view='dashboard';state.active=null;}
  const nav=state.role==='owner'?['dashboard','students','team','curriculum']:['dashboard','students','sessions','curriculum'];
  root.innerHTML=`<div class="shell"><aside class="sidebar"><a href="#" class="brand" data-view="dashboard">b<span>·</span><div>${ORG_NAME}<small>Ruang tumbuh bersama</small></div></a><div class="nav-label">RUANG KERJA</div><nav>${nav.map(k=>`<button class="nav-item ${state.view===k?'active':''}" data-view="${k}"><span aria-hidden="true">${icons[k]}</span>${labels[k]}${k==='sessions'?'<i>→</i>':''}</button>`).join('')}</nav><div class="sidebar-note"><span>✳</span><p>Setiap kemajuan<br>layak dirayakan.</p><small>Satu anak, satu perjalanan.</small></div><div class="account"><span class="avatar">${h(state.name.slice(0,1))}</span><div><strong>${h(state.name)}</strong><small>${state.role==='owner'?'Pemilik':'Guru pengajar'}</small></div><button title="Keluar" aria-label="Keluar" data-action="logout">↗</button></div></aside><main class="workspace"><header class="topbar"><span>${ORG_NAME} <span class="slash">/</span> ${labels[state.view]}</span><span class="date">${new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeZone:'Asia/Jakarta'}).format(new Date())}</span><div class="top-actions"><button data-action="refresh" title="Muat ulang data" aria-label="Muat ulang data">↻</button><button data-action="logout" aria-label="Keluar akun">Keluar ↗</button></div></header>${state.onboarding?'<div class="onboarding"><div><strong>Selamat datang, '+h(state.name)+'</strong><p>Mulai dari siswa yang ditugaskan, lalu buka sesi belajar saat siap.</p></div><button class="secondary" data-action="dismiss-onboarding">Mengerti</button></div>':''}${state.demo?'<div class="demo-banner">PRATINJAU · Data contoh, tidak tersimpan. <button data-action="logout">Kembali ke login →</button></div>':''}<section class="content">${({dashboard:dashboard,students:studentsView,sessions:sessionsView,team:teamView,curriculum:curriculumView})[state.view]()}</section><footer>${ORG_NAME} <span>Belajar bertumbuh, bersama.</span></footer></main></div><dialog id="modal"></dialog>`;
  restoreDrafts();scrollTo(0,y);
}
function heading(kicker,title,subtitle,button=''){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div>${button}</div>`;}
function ownerDashboard(){
  const active=state.students.filter(s=>s.status==='Aktif');
  const today=state.classes.filter(c=>c.date===localDate());
  const interventions=state.alerts.filter(a=>a.intervention);
  const sum=active.filter(ready);
  const pending=state.records.filter(r=>!r.finalized_at).length;
  const teachers=state.members.filter(m=>m.role==='teacher'&&m.active).length;
  return heading('PETA RUMAH BELAJAR','Halo, '+h(state.name.split(' ')[0])+' <span class="wave">✳</span>','Berikut hal penting yang membutuhkan perhatian Anda hari ini.','<button class="secondary" data-action="new-member">Kelola tim</button>')+
    '<div class="stats"><div class="stat"><span>Siswa aktif <i>◉</i></span><strong>'+active.length.toString().padStart(2,'0')+'</strong><small>Total perjalanan belajar</small></div><div class="stat"><span>Guru aktif <i>♧</i></span><strong>'+teachers.toString().padStart(2,'0')+'</strong><small>Tim yang mendampingi</small></div><div class="stat"><span>Sesi hari ini <i>▤</i></span><strong>'+today.length.toString().padStart(2,'0')+'</strong><small>Kelas yang berlangsung</small></div><div class="stat warm"><span>Perlu perhatian <i>♡</i></span><strong>'+interventions.length.toString().padStart(2,'0')+'</strong><small>Alarm untuk ditinjau</small></div></div>'+
    '<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><h2>Perlu keputusan</h2><p>Ringkasan pengecualian, bukan pekerjaan kelas.</p></div><span>✧</span></div>'+(interventions.length?interventions.map(a=>'<article class="attention-item"><span class="badge amber">Pendampingan khusus</span><h3>'+h(state.students.find(s=>s.id===a.student_id)?.name||'Siswa')+'</h3><p>Tiga kali mengulang di level yang sama. Tinjau bersama guru pendamping.</p></article>').join(''):'<article class="attention-item"><span class="badge green">Semua terkendali</span><h3>Tidak ada alarm intervensi</h3><p>Belum ada siswa yang membutuhkan keputusan khusus.</p></article>')+(sum.length?'<article class="attention-item"><span class="badge green">Siap sumatif</span><h3>'+sum.length+' siswa mencapai target</h3><p>Keputusan ujian sumatif dapat ditinjau saat diperlukan.</p></article>':'')+'</section><section class="panel"><div class="panel-heading"><div><h2>Ketertiban operasional</h2><p>Pemilik memantau; guru menyelesaikan.</p></div><span>◌</span></div><article class="attention-item"><span class="badge '+(pending?'amber':'green')+'">'+(pending?'Perlu ditinjau':'Rapi')+'</span><h3>'+(pending?pending+' sesi belum selesai dievaluasi':'Semua sesi sudah dievaluasi')+'</h3><p>Guru tetap menjadi pelaksana utama kegiatan kelas.</p></article></section></div>';
}
function dashboard(){
  if(state.role==='owner')return ownerDashboard();
  const active=state.students.filter(s=>s.status==='Aktif');const today=state.classes.filter(c=>c.date===localDate());const interventions=state.alerts.filter(a=>a.intervention);const sum=active.filter(ready);
  return `${heading('HARI BARU, KESEMPATAN BARU',`Halo, ${h(state.name.split(' ')[0])} <span class="wave">✳</span>`,'Mari temani langkah kecil yang berarti hari ini.','<button class="primary" data-action="new-session">＋ Mulai sesi kelas</button>')}<section class="welcome"><div><span class="pill light">BELAJAR SESUAI RITME ANAK</span><h2>Bukan siapa yang paling cepat.<br>Melainkan siapa yang terus bertumbuh.</h2><p>Kenali minatnya, dampingi prosesnya, rayakan kemajuannya.</p><button data-view="students">Lihat perjalanan siswa <span>↗</span></button></div><div class="growth-art" aria-hidden="true"><div class="orbit"></div><span class="petal p1"></span><span class="petal p2"></span><span class="petal p3"></span><span class="stem"></span><span class="art-label">TUMBUH DENGAN CARANYA</span></div></section><div class="stats"><div class="stat"><span>Siswa aktif <i>◉</i></span><strong>${active.length.toString().padStart(2,'0')}</strong><small>Perjalanan yang kita dampingi</small></div><div class="stat"><span>Sesi hari ini <i>▤</i></span><strong>${today.length.toString().padStart(2,'0')}</strong><small>Ruang untuk belajar bersama</small></div><div class="stat"><span>Siap ujian sumatif <i>✧</i></span><strong>${sum.length.toString().padStart(2,'0')}</strong><small>Target belajar sudah tercapai</small></div>${state.role==='owner'?`<div class="stat warm"><span>Butuh perhatian <i>♡</i></span><strong>${interventions.length.toString().padStart(2,'0')}</strong><small>Mari dampingi lebih dekat</small></div>`:''}</div><div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Perjalanan belajar</h2><button class="text-btn" data-view="students">Semua siswa →</button></div>${active.length?active.slice(0,5).map(studentRow).join(''):empty('Perjalanan dimulai di sini','Tambahkan siswa pertama untuk mulai mendampingi belajarnya.')}</section><section class="panel attention"><div class="panel-heading"><h2>Catatan untuk Anda</h2><span>✧</span></div>${state.role==='owner'&&interventions.length?interventions.map(a=>`<article class="attention-item"><span class="badge amber">Pendampingan khusus</span><h3>${h(state.students.find(s=>s.id===a.student_id)?.name)}</h3><p>Tiga kali mengulang di level yang sama. Tinjau pendekatan belajar dan diskusikan dengan guru.</p></article>`).join(''):'<article class="attention-item"><span class="badge green">Langkah hari ini</span><h3>Mulai dari rasa ingin tahu</h3><p>Gunakan minat anak sebagai pintu masuk sebelum mengenalkan tantangan baru.</p></article>'}${sum.length?`<article class="attention-item"><span class="badge green">Siap sumatif</span><h3>${sum.length} siswa mencapai target</h3><p>Buka profil siswa untuk mencatat hasil ujian akhir.</p></article>`:''}<div class="quote">“Kemajuan kecil tetaplah kemajuan.”<small>Pengingat untuk hari ini</small></div></section></div>`;
}
function studentRow(s){return `<button class="student-row" data-action="student" data-id="${s.id}"><span class="avatar pastel">${h(s.name[0])}</span><div class="student-info"><strong>${h(s.name)}</strong><small>${h(s.interest||'Minat belum diisi')}</small></div><div class="mini-progress"><small>Membaca <b>${s.reading_level}/${s.reading_target}</b></small><progress value="${progress(s.reading_level,s.reading_baseline,s.reading_target)}" max="100"></progress></div><span class="row-arrow">↗</span></button>`;}
function studentsView(){const list=state.students.filter(s=>s.name.toLowerCase().includes(state.filter.toLowerCase()));return `${heading('SETIAP ANAK UNIK','Kenali, lalu dampingi.','Profil, minat, dan perjalanan kompetensi setiap anak.',state.role==='owner'||state.role==='teacher'?'<button class="primary" data-action="new-student">＋ Tambah siswa</button>':'')}<div class="toolbar"><input id="student-search" type="search" placeholder="Cari nama siswa…" aria-label="Cari siswa" value="${h(state.filter)}"><span>${state.students.length} siswa terdaftar</span></div><div class="student-grid">${list.map(s=>`<article class="panel student-card"><div class="card-top"><span class="avatar large">${h(s.name[0])}</span><span class="badge ${ready(s)?'amber':'green'}">${h(s.status)}${ready(s)&&s.status==='Aktif'?' · Siap sumatif':''}</span></div><h2>${h(s.name)}</h2><p>${h(s.interest||'Minat belum diisi')}</p>${meter('Membaca',s.reading_level,s.reading_baseline,s.reading_target)}${meter('Matematika',s.math_level,s.math_baseline,s.math_target)}<button class="secondary full" data-action="student" data-id="${s.id}">Lihat profil & riwayat ↗</button></article>`).join('')||empty('Belum ada siswa','Data siswa yang ditugaskan kepada Anda akan tampil di sini.')}</div>`;}
function meter(label,current,baseline,target){return `<div class="meter"><div><span>${label}</span><strong>Level ${current} <small>/ ${target}</small></strong></div><progress value="${progress(current,baseline,target)}" max="100"></progress><small>Mulai level ${baseline} · ${progress(current,baseline,target)}% menuju target</small></div>`;}
function sessionsView(){
  const c=state.classes.find(c=>c.id===state.active);
  if(c)return `${heading('SATU RUANG, SEMUA KEBUTUHAN',h(c.theme),`${h(c.date)} · ${state.records.filter(r=>r.session_id===c.id).length} siswa`,'<button class="secondary" data-action="back-sessions">← Semua sesi</button>')}<div class="notice">Urutan mengajar: simpan kehadiran → buat panduan → dampingi anak → simpan evaluasi di akhir kelas → buat dan periksa rapor.</div><div class="session-list">${state.records.filter(r=>r.session_id===c.id).map(recordCard).join('')}</div>`;
  return `${heading('RUANG KELAS','Siap belajar bersama?','Satu sesi, materi sesuai level dan minat masing-masing anak.','<button class="primary" data-action="new-session">＋ Mulai sesi kelas</button>')}<div class="panel">${state.classes.map(c=>{const rr=state.records.filter(r=>r.session_id===c.id);return `<button class="class-row" data-action="open-session" data-id="${c.id}"><span class="calendar">${h(c.date.slice(8))}<small>${h(c.date.slice(0,7))}</small></span><div><h3>${h(c.theme)}</h3><p>${rr.length} siswa · ${rr.filter(r=>r.finalized_at).length} evaluasi selesai</p></div><span>Masuk kelas →</span></button>`;}).join('')||empty('Ruang kelas menanti','Pilih siswa dan tema untuk membuka sesi pertama.')}</div>`;
}
function recordCard(r){
  const s=studentFor(r);if(!s)return '';
  const targets=assessmentsFor(r.id);const link=waLink(s.phone,r.report);
  const targetText=targets.length?targets.map(a=>`${subjectLabels[a.subject]} ${a.level_snapshot}`).join(' · '):`Membaca ${r.reading_snapshot} · Matematika ${r.math_snapshot}`;
  const ratings=[['','Pilih perkembangan'],['BT','Belum tampak'],['MB','Mulai berkembang'],['T','Tercapai']];
  const evaluation=targets.length?targets.map(a=>`<div class="target-eval"><div><span class="badge green">${h(subjectLabels[a.subject])} · Level ${a.level_snapshot}</span><small>Dua bukti Tercapai dibutuhkan sebelum naik level.</small></div>${select('Perkembangan',`rating_${a.subject}`,ratings,a.rating||'',r.finalized_at?'disabled':'required')}${area('Bukti singkat (opsional)',`note_${a.subject}`,a.evidence_note||'',`maxlength="1000" ${r.finalized_at?'disabled':''}`)}</div>`).join(''):select('Perkembangan hari ini','grade',[['','Pilih penilaian'],['SB','Sangat Baik'],['BSH','Berkembang Sesuai Harapan'],['MB','Mulai Berkembang']],r.grade||'',r.finalized_at?'disabled':'required');
  return `<article class="panel session-card"><div class="panel-heading"><div><h2>${h(s.name)}</h2><p>${h(s.interest)} · ${h(targetText)}</p></div><span class="badge ${r.finalized_at?'green':'amber'}">${r.finalized_at?'Evaluasi tersimpan':'Sesi berlangsung'}</span></div><form data-form="attendance" data-id="${r.id}" class="inline-form">${select('Kehadiran','attendance',['Hadir','Sakit','Izin','Alfa'],r.attendance,r.finalized_at?'disabled':'')}<button class="secondary" ${r.finalized_at?'disabled':''}>Simpan kehadiran</button></form>${r.attendance==='Hadir'?`<section class="lesson"><div class="section-title"><h3>01 / Panduan mengajar</h3><button class="secondary" data-action="generate" data-kind="material" data-id="${r.id}">${r.material?'Lihat panduan tersimpan':'✧ Buat panduan AI'}</button></div>${r.material?`<pre>${h(r.material)}</pre><button class="text-btn" data-action="print" data-id="${r.id}">Cetak panduan (opsional)</button>`:'<p class="muted">Panduan berfokus pada dua kompetensi inti dan satu kompetensi lintas bidang.</p>'}</section>`:''}<form data-form="evaluation" data-id="${r.id}" class="evaluation competency-evaluation"><h3>02 / Bukti perkembangan</h3>${evaluation}${area('Catatan anekdot umum (opsional)','anecdote',r.anecdote,`maxlength="3000" ${r.finalized_at?'disabled':''}`)}<button class="primary" ${r.finalized_at?'disabled':''}>${r.finalized_at?'✓ Evaluasi sudah tersimpan':'Simpan & selesaikan evaluasi'}</button><small class="fine">Setiap kompetensi dinilai mandiri. Hanya kompetensi dengan dua bukti Tercapai yang naik satu level.</small></form><section class="report"><div class="section-title"><h3>03 / Kabar untuk orang tua</h3>${r.attendance==='Hadir'?`<button class="secondary" data-action="generate" data-kind="report" data-id="${r.id}" ${!r.finalized_at?'disabled':''}>${r.report?'Lihat rapor tersimpan':'✧ Buat draf rapor'}</button>`:''}</div>${r.report?`<pre>${h(r.report)}</pre><div class="button-row"><button class="secondary" data-action="copy" data-id="${r.id}">Salin pesan</button>${link?`<a class="primary" target="_blank" rel="noopener noreferrer" href="${h(link)}">Periksa & buka WhatsApp ↗</a>`:'<small>Lengkapi nomor WhatsApp di profil siswa untuk membuka percakapan.</small>'}</div>`:'<p class="muted">Rapor dibuat setelah evaluasi agar kabarnya sesuai kegiatan nyata.</p>'}</section></article>`;}
function teamView(){return `${heading('TIM YANG SALING MENDUKUNG','Guru yang mendampingi.','Daftarkan email guru, lalu tugaskan siswa yang dapat mereka akses.','<button class="primary" data-action="new-member">＋ Daftarkan guru</button>')}<div class="panel">${state.members.map(m=>`<div class="class-row"><span class="avatar">${h(m.name[0])}</span><div><h3>${h(m.name)}</h3><p>${h(m.email)} · ${m.role==='owner'?'Pemilik':'Guru'} · ${m.active?'Aktif':'Nonaktif'}</p></div>${m.role==='teacher'?`<button class="secondary" data-action="toggle-member" data-id="${h(m.email)}">${m.active?'Nonaktifkan':'Aktifkan'}</button>`:''}</div>`).join('')||empty('Belum ada guru','Tambahkan email guru. Guru kemudian mengaktifkan akun melalui halaman login.')}</div><div class="notice">Guru mengaktifkan akun menggunakan email yang didaftarkan di sini. Penugasan siswa tersedia di profil siswa setelah guru mengaktifkan akun.</div>`;}
function curriculumView(){const phase=level=>level<=4?'Fondasi':level<=8?'Fase A · SD 1–2':level<=12?'Fase B · SD 3–4':'Fase C · SD 5–6';return `${heading('TANGGA KOMPETENSI','16 level, bukti yang jelas.','Tujuan dan kriteria keberhasilan menjadi acuan tetap; AI hanya membuat aktivitas sesuai tema dan minat.')}<div class="notice">Level adalah posisi kompetensi, bukan label kemampuan anak atau pengganti kelas sekolah. Bahasa Inggris merupakan pengayaan dan tidak wajib untuk kelulusan.</div><div class="curriculum-grid">${state.curriculum.map(c=>`<article class="panel curriculum-card"><span class="badge green">LEVEL ${c.level}</span><h2>${phase(c.level)}</h2>${subjects.map(k=>`<details><summary>${h(subjectLabels[k])}</summary><p>${h(c[k])}</p><small><strong>Bukti berhasil</strong><br>${h(c[`${k}_criteria`]||'Kriteria belum tersedia.')}</small></details>`).join('')}${state.role==='owner'?`<button class="secondary" data-action="edit-curriculum" data-id="${c.level}">Edit tujuan & kriteria</button>`:''}</article>`).join('')||empty('Bank kurikulum','Enam belas level kurikulum akan tersedia setelah database terhubung.')}</div>`;}
function modal(title,body){const d=document.querySelector('#modal');d.innerHTML=`<div class="modal-head"><h2>${title}</h2><button data-action="close" aria-label="Tutup">✕</button></div>${body}`;d.showModal();}
function competencyMeters(s){const rows=competenciesFor(s.id);return rows.length?`<div class="competency-list">${rows.map(c=>`<div class="competency-meter"><div><strong>${h(subjectLabels[c.subject])}</strong><span>Level ${c.current_level} / ${c.target}${c.required?'':' · pengayaan'}</span></div><progress value="${progress(c.current_level,c.baseline,c.target)}" max="100"></progress><small>${c.evidence_count}/2 bukti menuju kenaikan berikutnya${c.intervention?' · perlu ditinjau':''}</small></div>`).join('')}</div>`:`${meter('Membaca',s.reading_level,s.reading_baseline,s.reading_target)}${meter('Matematika',s.math_level,s.math_baseline,s.math_target)}`;}
function competencyTargetsForm(s){const rows=competenciesFor(s.id);return rows.length?`<form data-form="competency-targets" data-id="${s.id}"><h3>Target per kompetensi</h3><p class="muted">Target tidak boleh lebih rendah dari level saat ini. Bahasa Inggris tetap pengayaan.</p><div class="form-grid">${rows.map(c=>field(subjectLabels[c.subject],`target_${c.subject}`,'number',c.target,`required min="${c.current_level}" max="16"`)).join('')}</div><button class="secondary">Simpan target kompetensi</button></form>`:'';}
function studentForm(s={}){const owner=state.role==='owner';const canCreate=owner||state.role==='teacher';const edit=!!s.id;modal(edit?h(s.name):'Siswa baru',`<form data-form="student" data-id="${s.id||''}"><fieldset ${canCreate?'':'disabled'}><div class="form-grid">${field('Nama anak','name','text',s.name,'required maxlength="120"')}${field('Sapaan orang tua','parent_name','text',s.parent_name,'required maxlength="120"')}${field('Nomor WhatsApp','phone','tel',s.phone)}${field('Minat / hobi','interest','text',s.interest,'required maxlength="300"')}</div>${area('Hasil diagnostik awal','diagnostic',s.diagnostic,'maxlength="3000"')}${area('Catatan gaya belajar','learning_notes',s.learning_notes,'maxlength="3000"')}<div class="form-grid">${field(edit?'Level awal membaca (terkunci)':'Level awal membaca','reading_baseline','number',s.reading_baseline||1,`min="1" max="16" required ${edit?'disabled':''}`)}${field('Target membaca','reading_target','number',s.reading_target||7,'min="1" max="16" required')}${field(edit?'Level awal matematika (terkunci)':'Level awal matematika','math_baseline','number',s.math_baseline||1,`min="1" max="16" required ${edit?'disabled':''}`)}${field('Target matematika','math_target','number',s.math_target||7,'min="1" max="16" required')}</div>${edit?select('Status','status',s.status==='Lulus'?['Lulus','Non-Aktif']:['Aktif','Non-Aktif'],s.status):''}</fieldset>${canCreate?'<button class="primary full">Simpan profil siswa</button>':''}</form>${edit?`<hr><h3>Perjalanan per kompetensi</h3>${competencyMeters(s)}${owner?`<hr>${competencyTargetsForm(s)}<hr><form data-form="assign" data-id="${s.id}"><h3>Guru pendamping</h3>${state.profiles.filter(p=>state.members.some(m=>m.email===p.email&&m.role==='teacher'&&m.active)).map(p=>`<label class="check"><input type="checkbox" name="teacher" value="${p.id}" ${state.assignments.some(a=>a.student_id===s.id&&a.teacher_id===p.id)?'checked':''}>${h(p.name)}</label>`).join('')||'<p>Belum ada guru yang mengaktifkan akun.</p>'}<button class="secondary">Simpan penugasan</button></form>`:''}${owner&&ready(s)&&s.status==='Aktif'?`<hr><form data-form="summative" data-id="${s.id}"><h3>Ujian sumatif akhir</h3>${field('Nilai akhir (1–100)','score','number',s.summative_score||'','required min="1" max="100"')}${select('Keputusan pemilik','pass',[['false','Perlu pendampingan lanjutan'],['true','Lulus']], 'false')}<button class="primary">Simpan hasil sumatif</button></form>`:''}<hr><h3>Riwayat evaluasi</h3>${state.records.filter(r=>r.student_id===s.id&&r.finalized_at).sort((a,b)=>b.finalized_at.localeCompare(a.finalized_at)).map(r=>`<p class="history">${h(state.classes.find(c=>c.id===r.session_id)?.date||r.finalized_at.slice(0,10))} · ${h(r.attendance)} · <strong>${h(r.grade||'Tanpa nilai')}</strong><br><small>${h(r.anecdote)}</small></p>`).join('')||'<p class="muted">Belum ada evaluasi tersimpan.</p>'}`:''}`);}
function newSession(){const available=state.students.filter(s=>s.status==='Aktif'&&!state.records.some(r=>r.student_id===s.id&&!r.finalized_at));modal('Mulai sesi kelas',`<form data-form="session" data-id="${crypto.randomUUID()}">${field('Tanggal','date','date',localDate(),'required')}${field('Tema bersama','theme','text',state.themes[0]?.name||'','required maxlength="120" list="themes"')}<datalist id="themes">${state.themes.map(t=>`<option value="${h(t.name)}">`).join('')}</datalist><h3>Pilih anak yang mengikuti sesi</h3>${available.map(s=>`<label class="check"><input type="checkbox" name="student" value="${s.id}">${h(s.name)} <small>Membaca ${s.reading_level} · Berhitung ${s.math_level}</small></label>`).join('')||'<p>Belum ada siswa tersedia. Tambahkan siswa atau selesaikan sesi yang masih terbuka.</p>'}<button class="primary full" ${available.length?'':'disabled'}>Buka ruang kelas →</button></form>`);}
function areaProgress(s,codes){
  const rows=activeCompetenciesFor(s.id).filter(c=>codes.includes(c.subject));
  if(!rows.length)return null;
  return {baseline:Math.round(rows.reduce((n,c)=>n+c.baseline,0)/rows.length),current:Math.round(rows.reduce((n,c)=>n+c.current_level,0)/rows.length),target:Math.round(rows.reduce((n,c)=>n+c.target,0)/rows.length)};
}
function studentRowV2(s){
  const bi=areaProgress(s,['listening','speaking','reading','writing'])||{current:s.reading_level,target:s.reading_target};
  return `<button class="student-row" data-action="student" data-id="${s.id}"><span class="avatar pastel">${h(s.name[0])}</span><div class="student-info"><strong>${h(s.name)}</strong><small>${h(s.interest||'Minat belum diisi')}</small></div><div class="mini-progress"><small>Bahasa Indonesia <b>${bi.current}/${bi.target}</b></small><progress value="${progress(bi.current,bi.baseline||1,bi.target)}" max="100"></progress></div><span class="row-arrow">→</span></button>`;
}
function studentsViewV2(){
  const list=state.students.filter(s=>s.name.toLowerCase().includes(state.filter.toLowerCase()));
  return `${heading('SETIAP ANAK UNIK','Kenali, lalu dampingi.','Profil dan perjalanan kompetensi setiap anak.',state.role==='teacher'?'<button class="primary" data-action="new-student">＋ Tambah siswa</button>':'')}<div class="toolbar"><input id="student-search" type="search" placeholder="Cari nama siswa…" aria-label="Cari siswa" value="${h(state.filter)}"><span>${state.students.length} siswa terdaftar</span></div><div class="student-grid">${list.map(s=>{const bi=areaProgress(s,['listening','speaking','reading','writing'])||{baseline:s.reading_baseline,current:s.reading_level,target:s.reading_target};const ipas=activeCompetenciesFor(s.id).find(c=>c.subject==='ipas');return `<article class="panel student-card"><div class="card-top"><span class="avatar large">${h(s.name[0])}</span><span class="badge ${ready(s)?'amber':'green'}">${h(s.status)}${ready(s)&&s.status==='Aktif'?' · Siap sumatif':''}</span></div><h2>${h(s.name)}</h2><p>${h(s.interest||'Minat belum diisi')}</p>${meter('Bahasa Indonesia',bi.current,bi.baseline,bi.target)}${meter('Matematika',s.math_level,s.math_baseline,s.math_target)}${ipas?meter('IPAS',ipas.current_level,ipas.baseline,ipas.target):''}<button class="secondary full" data-action="student" data-id="${s.id}">Lihat profil & riwayat →</button></article>`;}).join('')||empty('Belum ada siswa',state.role==='owner'?'Siswa baru ditambahkan oleh guru dan akan tampil di sini.':'Data siswa yang ditugaskan kepada Anda akan tampil di sini.')}</div>`;
}
function sessionsViewV2(){
  const c=state.classes.find(c=>c.id===state.active);
  if(c){
    const records=state.records.filter(r=>r.session_id===c.id);
    const groups=[...new Set(records.filter(r=>r.attendance==='Hadir').map(r=>r.group_no||1))].sort();
    const done=records.filter(r=>r.finalized_at).length;
    return `${heading('SATU TEMA, BERAGAM TANTANGAN',h(c.theme),`${h(c.date)} · ${c.duration_minutes||60} menit · ${groups.length||1} kelompok · ${done} dari ${records.length} anak selesai dievaluasi`,'<button class="secondary" data-action="back-sessions">← Semua sesi</button>')}<div class="notice"><strong>Langkah kelas</strong><br>① Tandai anak yang tidak datang. Kehadiran bisa diubah sampai evaluasinya disimpan, dan panduan kelas tetap aman.<br>② Buat panduan kelas sekali untuk semua kelompok.<br>③ Setelah kegiatan, simpan evaluasi setiap anak, termasuk yang tidak hadir.<br>④ Buat kabar orang tua, periksa, lalu kirim lewat WhatsApp.</div><article class="panel class-guide"><div class="section-title"><div><h2>Panduan kelas bersama</h2><p>Satu alur mengajar dengan kartu kegiatan untuk maksimal tiga kelompok.</p></div><button class="primary" data-action="generate-class" data-id="${c.id}">${c.material?'Lihat panduan tersimpan':'✦ Buat panduan kelas AI'}</button></div>${c.material?`<pre>${h(c.material)}</pre><button class="text-btn" data-action="print-class" data-id="${c.id}">Cetak panduan (opsional)</button>`:'<p class="muted">Panduan akan mengatur waktu, aktivitas tematik, diferensiasi kelompok, English Exposure, dan titik observasi karakter.</p>'}</article><h2 class="student-evaluation-title">Evaluasi individual</h2><div class="session-list">${records.map(recordCardV2).join('')}</div>`;
  }
  return `${heading('RUANG KELAS','Siap belajar bersama?','Satu tema, satu panduan multigrade, dan bukti perkembangan individual.','<button class="primary" data-action="new-session">＋ Mulai sesi kelas</button>')}<div class="panel">${state.classes.map(x=>{const rr=state.records.filter(r=>r.session_id===x.id);return `<button class="class-row" data-action="open-session" data-id="${x.id}"><span class="calendar">${h(x.date.slice(8))}<small>${h(x.date.slice(0,7))}</small></span><div><h3>${h(x.theme)}</h3><p>${x.duration_minutes||60} menit · ${rr.length} siswa · ${rr.filter(r=>r.finalized_at).length} evaluasi selesai</p></div><span>Masuk kelas →</span></button>`;}).join('')||empty('Ruang kelas menanti','Pilih durasi, tema, dan siswa untuk membuka sesi pertama.')}</div>`;
}
function recordCardV2(r){
  const s=studentFor(r);if(!s)return '';
  const targets=assessmentsFor(r.id);const observation=observationFor(r.id);const link=waLink(s.phone,r.report);const locked=!!r.finalized_at;const absent=r.attendance!=='Hadir';
  const targetText=targets.map(a=>`${subjectLabels[a.subject]||a.subject} ${a.level_snapshot}`).join(' · ');
  const ratings=[['','Pilih perkembangan'],['BT','Belum tampak'],['MB','Mulai berkembang'],['T','Tercapai']];
  const englishRatings=[['','Tidak dicatat'],['BT','Belum merespons'],['MB','Mulai merespons'],['T','Menggunakan/merespons']];
  const evaluation=targets.map(a=>`<div class="target-eval"><div><span class="badge green">${h(subjectLabels[a.subject]||a.subject)} · Level ${a.level_snapshot}</span><small>Dua bukti Tercapai dibutuhkan sebelum naik level.</small></div>${select('Perkembangan',`rating_${a.subject}`,ratings,a.rating||'',locked||absent?'disabled':'required')}${area('Bukti singkat',`note_${a.subject}`,a.evidence_note||'',`maxlength="1000" ${locked||absent?'disabled':''}`)}</div>`).join('');
  const absentForm=`<form data-form="evaluation" data-id="${r.id}" class="evaluation competency-evaluation"><h3>01 / Selesaikan catatan</h3><p class="muted">${h(s.name)} tercatat ${h(r.attendance)}. Tidak ada penilaian dan level tidak berubah. ${locked?'':'Tekan tombol di bawah agar anak dapat ikut sesi berikutnya.'}</p>${area('Catatan (opsional)','anecdote',r.anecdote||'',`maxlength="3000" ${locked?'disabled':''}`)}<button class="primary" ${locked?'disabled':''}>${locked?'✓ Sudah diselesaikan':'Selesaikan untuk anak tidak hadir'}</button></form>`;
  const chars=Object.entries(characterLabels).map(([value,label])=>`<label class="check"><input type="checkbox" name="character" value="${value}" ${(observation.character_dimensions||[]).includes(value)?'checked':''} ${locked?'disabled':''}>${label}</label>`).join('');
  return `<article class="panel session-card"><div class="panel-heading"><div><h2>${h(s.name)} <small>· Kelompok ${r.group_no||1}</small></h2><p>${h(s.interest||'Minat belum diisi')} · ${h(targetText)}</p></div><span class="badge ${locked?'green':'amber'}">${locked?'Evaluasi tersimpan':'Sesi berlangsung'}</span></div><form data-form="attendance" data-id="${r.id}" class="inline-form">${select('Kehadiran','attendance',['Hadir','Sakit','Izin','Alfa'],r.attendance,locked?'disabled':'')}<button class="secondary" ${locked?'disabled':''}>Simpan kehadiran</button></form>${absent?absentForm:`<form data-form="evaluation" data-id="${r.id}" class="evaluation competency-evaluation"><h3>01 / Bukti target inti</h3>${evaluation}<div class="observation-block"><h3>02 / English Exposure</h3><p class="muted">Dicatat sebagai pengayaan tematik dan tidak menentukan kelulusan.</p>${select('Respons Bahasa Inggris','english_rating',englishRatings,observation.english_rating||'',locked?'disabled':'')}${area('Bukti English Exposure (opsional)','english_note',observation.english_note||'',`maxlength="1000" ${locked?'disabled':''}`)}</div><div class="observation-block"><h3>03 / Observasi karakter</h3><p class="muted">Pilih perilaku yang terlihat dalam kegiatan; ini bukan nilai atau level anak.</p><div class="character-checks">${chars}</div>${area('Konteks observasi karakter (opsional)','character_note',observation.character_note||'',`maxlength="1000" ${locked?'disabled':''}`)}</div>${area('Catatan anekdot umum (opsional)','anecdote',r.anecdote||'',`maxlength="3000" ${locked?'disabled':''}`)}<button class="primary" ${locked?'disabled':''}>${locked?'✓ Evaluasi sudah tersimpan':'Simpan & selesaikan evaluasi'}</button><small class="fine">Target inti dinilai mandiri. English Exposure dan karakter dicatat tanpa menjadi syarat kelulusan.</small></form>`}<section class="report"><div class="section-title"><h3>${absent?'02':'04'} / Kabar untuk orang tua</h3>${r.attendance==='Hadir'?`<button class="secondary" data-action="generate" data-kind="report" data-id="${r.id}" ${!locked?'disabled':''}>${r.report?'Lihat rapor tersimpan':'✦ Buat draf rapor'}</button>`:''}</div>${r.report?`<pre>${h(r.report)}</pre><div class="button-row"><button class="secondary" data-action="copy" data-id="${r.id}">Salin pesan</button>${link?`<a class="primary" target="_blank" rel="noopener noreferrer" href="${h(link)}">Periksa & buka WhatsApp →</a>`:'<small>Lengkapi nomor WhatsApp di profil siswa untuk membuka percakapan.</small>'}</div>`:'<p class="muted">Rapor dibuat setelah evaluasi agar kabarnya sesuai kegiatan nyata.</p>'}</section></article>`;
}
function curriculumViewV2(){
  const phase=level=>level<=4?'Fondasi':level<=8?'Fase A · SD 1–2':level<=12?'Fase B · SD 3–4':'Fase C · SD 5–6';
  const detail=(c,k)=>`<details><summary>${h(subjectLabels[k])}</summary><p>${h(c[k])}</p><small><strong>Bukti berhasil</strong><br>${h(c[`${k}_criteria`]||'Kriteria belum tersedia.')}</small></details>`;
  return `${heading('TANGGA KOMPETENSI','16 level yang saling berulang dan bertumbuh.','Tujuan tetap; aktivitas berubah mengikuti tema, kelompok, dan kebutuhan anak.')}<div class="notice">Bahasa Indonesia terdiri dari menyimak, berbicara, membaca, dan menulis. English Exposure wajib hadir dalam tema, tetapi tidak menjadi syarat kelulusan. Karakter diamati pada semua kegiatan.</div><div class="curriculum-grid">${state.curriculum.map(c=>`<article class="panel curriculum-card"><span class="badge green">LEVEL ${c.level}</span><h2>${phase(c.level)}</h2><h3>Bahasa Indonesia</h3>${['listening','speaking','reading','writing'].map(k=>detail(c,k)).join('')}<h3>Matematika</h3>${detail(c,'math')}<h3>IPAS tematik</h3>${detail(c,'ipas')}<h3>English Exposure</h3>${detail(c,'english')}${state.role==='owner'?`<button class="secondary" data-action="edit-curriculum" data-id="${c.level}">Edit tujuan & kriteria</button>`:''}</article>`).join('')||empty('Bank kurikulum','Enam belas level kurikulum akan tersedia setelah database terhubung.')}</div>`;
}
function competencyMetersV2(s){
  const rows=activeCompetenciesFor(s.id);
  if(!rows.length)return `${meter('Bahasa Indonesia',s.reading_level,s.reading_baseline,s.reading_target)}${meter('Matematika',s.math_level,s.math_baseline,s.math_target)}`;
  const order=['listening','speaking','reading','writing','math','ipas','english'];
  return `<div class="competency-list">${order.map(code=>rows.find(c=>c.subject===code)).filter(Boolean).map(c=>`<div class="competency-meter"><div><strong>${h(subjectLabels[c.subject])}</strong><span>Level ${c.current_level} / ${c.target}${c.required?'':' · pengayaan'}</span></div><progress value="${progress(c.current_level,c.baseline,c.target)}" max="100"></progress><small>${c.evidence_count}/2 bukti menuju kenaikan berikutnya${c.intervention?' · perlu ditinjau':''}</small></div>`).join('')}</div>`;
}
function competencyTargetsFormV2(s){const rows=activeCompetenciesFor(s.id);return rows.length?`<form data-form="competency-targets" data-id="${s.id}"><h3>Target per kompetensi</h3><p class="muted">Empat elemen Bahasa Indonesia, Matematika, dan IPAS wajib. English Exposure tetap pengayaan.</p><div class="form-grid">${rows.map(c=>field(subjectLabels[c.subject],`target_${c.subject}`,'number',c.target,`required min="${c.current_level}" max="16"`)).join('')}</div><button class="secondary">Simpan target kompetensi</button></form>`:'';}
function studentFormV2(s={}){
  const owner=state.role==='owner';const canCreate=state.role==='teacher'||(owner&&!!s.id);const edit=!!s.id;
  modal(edit?h(s.name):'Siswa baru',`<form data-form="student" data-id="${s.id||''}"><fieldset ${canCreate?'':'disabled'}><div class="form-grid">${field('Nama anak','name','text',s.name,'required maxlength="120"')}${field('Sapaan orang tua','parent_name','text',s.parent_name,'required maxlength="120"')}${field('Nomor WhatsApp','phone','tel',s.phone)}${field('Minat / hobi','interest','text',s.interest,'required maxlength="300"')}</div>${area('Hasil diagnostik awal','diagnostic',s.diagnostic,'maxlength="3000"')}${area('Catatan gaya belajar','learning_notes',s.learning_notes,'maxlength="3000"')}<div class="form-grid">${field(edit?'Level awal Bahasa Indonesia (terkunci)':'Level awal Bahasa Indonesia','reading_baseline','number',s.reading_baseline||1,`min="1" max="16" required ${edit?'disabled':''}`)}${field('Target awal Bahasa Indonesia & IPAS','reading_target','number',s.reading_target||7,'min="1" max="16" required')}${field(edit?'Level awal Matematika (terkunci)':'Level awal Matematika','math_baseline','number',s.math_baseline||1,`min="1" max="16" required ${edit?'disabled':''}`)}${field('Target Matematika','math_target','number',s.math_target||7,'min="1" max="16" required')}</div>${edit?select('Status','status',s.status==='Lulus'?['Lulus','Non-Aktif']:['Aktif','Non-Aktif'],s.status):''}</fieldset>${canCreate?'<button class="primary full">Simpan profil siswa</button>':''}</form>${edit?`<hr><h3>Perjalanan kompetensi</h3>${competencyMetersV2(s)}<div class="notice">Karakter tidak diberi level. Guru mencatat perilaku yang tampak dalam konteks kegiatan.</div>${owner?`<hr>${competencyTargetsFormV2(s)}<hr><form data-form="assign" data-id="${s.id}"><h3>Guru pendamping</h3>${state.profiles.filter(p=>state.members.some(m=>m.email===p.email&&m.role==='teacher'&&m.active)).map(p=>`<label class="check"><input type="checkbox" name="teacher" value="${p.id}" ${state.assignments.some(a=>a.student_id===s.id&&a.teacher_id===p.id)?'checked':''}>${h(p.name)}</label>`).join('')||'<p>Belum ada guru yang mengaktifkan akun.</p>'}<button class="secondary">Simpan penugasan</button></form>`:''}${owner&&ready(s)&&s.status==='Aktif'?`<hr><form data-form="summative" data-id="${s.id}"><h3>Ujian sumatif akhir</h3>${field('Nilai akhir (1–100)','score','number',s.summative_score||'','required min="1" max="100"')}${select('Keputusan pemilik','pass',[['false','Perlu pendampingan lanjutan'],['true','Lulus']],'false')}<button class="primary">Simpan hasil sumatif</button></form>`:''}<hr><h3>Riwayat evaluasi</h3>${state.records.filter(r=>r.student_id===s.id&&r.finalized_at).sort((a,b)=>b.finalized_at.localeCompare(a.finalized_at)).map(r=>`<p class="history">${h(state.classes.find(c=>c.id===r.session_id)?.date||r.finalized_at.slice(0,10))} · ${h(r.attendance)} · <strong>${h(r.grade||'Tanpa nilai')}</strong><br><small>${h(r.anecdote)}</small></p>`).join('')||'<p class="muted">Belum ada evaluasi tersimpan.</p>'}`:''}`);
}
function newSessionV2(){
  const available=state.students.filter(s=>s.status==='Aktif'&&!state.records.some(r=>r.student_id===s.id&&!r.finalized_at));
  modal('Mulai sesi kelas',`<form data-form="session" data-id="${crypto.randomUUID()}">${field('Tanggal','date','date',localDate(),'required')}${select('Durasi kelas','duration',[['60','60 menit · 2 target inti'],['75','75 menit · 2 target + integrasi'],['90','90 menit · maksimal 3 target']],'60','required')}${field('Tema bersama','theme','text',state.themes[0]?.name||'','required maxlength="120" list="themes"')}<datalist id="themes">${state.themes.map(t=>`<option value="${h(t.name)}">`).join('')}</datalist><div class="notice">Sistem memilih target spiral bersama dan membagi siswa menjadi maksimal tiga kelompok berdasarkan posisi kompetensi.</div><h3>Pilih anak yang mengikuti sesi</h3>${available.map(s=>`<label class="check"><input type="checkbox" name="student" value="${s.id}">${h(s.name)} <small>Bahasa Indonesia ${s.reading_level} · Matematika ${s.math_level}</small></label>`).join('')||'<p>Belum ada siswa tersedia. Tambahkan siswa atau selesaikan sesi yang masih terbuka.</p>'}<button class="primary full" ${available.length?'':'disabled'}>Buka ruang kelas →</button></form>`);
}

studentRow=studentRowV2;
studentsView=studentsViewV2;
sessionsView=sessionsViewV2;
recordCard=recordCardV2;
curriculumView=curriculumViewV2;
competencyMeters=competencyMetersV2;
competencyTargetsForm=competencyTargetsFormV2;
studentForm=studentFormV2;
newSession=newSessionV2;

document.addEventListener('click',async e=>{
  const b=e.target.closest('[data-action],[data-view]');if(!b)return;e.preventDefault();
  if(b.dataset.view){state.view=b.dataset.view;state.active=null;render();return;}
  const {action,id,kind}=b.dataset;
  try{
    if(action==='demo')return demo();
    if(action==='dismiss-onboarding'){localStorage.setItem('rb-onboarding-'+state.user.id,'1');state.onboarding=false;return render();}
    if(action==='refresh'){await refresh();return notify('Data terbaru sudah dimuat.');}
    if(action==='logout'){drafts.clear();if(db&&!state.demo)await db.auth.signOut();Object.assign(state,{user:null,demo:false,students:[],records:[],alerts:[],members:[]});return login();}
    if(action==='close')return document.querySelector('#modal').close();
    if(action==='student')return studentForm(state.students.find(s=>s.id===id));
    if(action==='new-student'){if(state.role!=='teacher')return notify('Siswa baru ditambahkan oleh guru.',true);return studentForm();}
    if(action==='new-session')return newSession();
    if(action==='open-session'){state.active=id;return render();}
    if(action==='back-sessions'){state.active=null;return render();}
    if(action==='new-member')return modal('Daftarkan guru',`<form data-form="member">${field('Nama guru','name','text','','required maxlength="120"')}${field('Email guru','email','email','','required')}<button class="primary full">Daftarkan email guru</button></form>`);
    if(action==='edit-curriculum'){const c=state.curriculum.find(c=>c.level===Number(id));return modal(`Kurikulum level ${id}`,`<form data-form="curriculum" data-id="${id}">${subjects.map(k=>`<fieldset class="curriculum-edit"><h3>${h(subjectLabels[k])}</h3>${area('Tujuan kompetensi',k,c[k],'required maxlength="2000"')}${area('Bukti keberhasilan',`${k}_criteria`,c[`${k}_criteria`],'required maxlength="2000"')}</fieldset>`).join('')}<button class="primary">Simpan kurikulum</button></form>`);}
    if(action==='copy'){await navigator.clipboard.writeText(state.records.find(r=>r.id===id).report);return notify('Pesan berhasil disalin.');}
    if(action==='print'){document.querySelectorAll('.session-card').forEach(el=>el.classList.toggle('print-target',!!el.querySelector(`[data-id="${id}"]`)));return window.print();}
    guardDemo();b.disabled=true;
    if(action==='generate-class'){
      const c=state.classes.find(c=>c.id===id);if(c?.material)return notify('Panduan kelas tersimpan sudah tampil.');
      b.textContent='Sedang menyusun…';const {data,error}=await db.functions.invoke('generate-learning',{body:{session_id:id,kind:'class_material'}});
      if(error){let detail;try{detail=await error.context?.json();}catch{}throw new Error(detail?.error||error.message);}if(data?.error)throw new Error(data.error);
      await refresh();return notify('Panduan kelas tersimpan. Periksa sebelum digunakan.');
    }
    if(action==='print-class'){document.querySelector('.class-guide')?.classList.add('print-target');return window.print();}
    if(action==='register'){const form=document.querySelector('#login-form');if(!form.reportValidity())return;const f=new FormData(form);await result(db.auth.signUp({email:f.get('email'),password:f.get('password'),options:{emailRedirectTo:location.origin+location.pathname}}));notify('Aktivasi diterima. Periksa email konfirmasi, lalu masuk.');}
    if(action==='toggle-member'){const m=state.members.find(m=>m.email===id);await result(db.from('access_list').update({active:!m.active}).eq('email',id));await refresh();}
    if(action==='generate'){const r=state.records.find(r=>r.id===id);if(r[kind==='material'?'material':'report'])return notify('Hasil tersimpan sudah tampil di kartu ini.');b.textContent='Sedang menyusun…';const {data,error}=await db.functions.invoke('generate-learning',{body:{record_id:id,kind}});if(error){let detail;try{detail=await error.context?.json();}catch{}throw new Error(detail?.error||error.message);}if(data?.error)throw new Error(data.error);await refresh();notify('Hasil AI tersimpan. Periksa isinya sebelum digunakan.');}
  }catch(err){notify(err.message,true);}finally{b.disabled=false;}
});
document.addEventListener('input',e=>{if(e.target.id==='student-search'){state.filter=e.target.value;const pos=e.target.selectionStart;render();const input=document.querySelector('#student-search');input.focus();try{input.setSelectionRange(pos,pos);}catch{}}});
document.addEventListener('submit',async e=>{
  e.preventDefault();const form=e.target;const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);
  try{
    guardDemo();const f=new FormData(form);const v=Object.fromEntries(f);const id=form.dataset.id;
    if(form.id==='login-form'){const data=await result(db.auth.signInWithPassword({email:v.email,password:v.password}));await loadUser(data.user);return;}
    switch(form.dataset.form){
      case 'student':{const payload={name:v.name.trim(),parent_name:v.parent_name.trim(),phone:v.phone,interest:v.interest,diagnostic:v.diagnostic,learning_notes:v.learning_notes,reading_target:Number(v.reading_target),math_target:Number(v.math_target)};if(id){payload.status=v.status;await result(db.from('students').update(payload).eq('id',id));}else{Object.assign(payload,{reading_baseline:Number(v.reading_baseline),math_baseline:Number(v.math_baseline)});await result(db.rpc('create_student',{p_payload:payload}));}break;}
      case 'session':{const ids=f.getAll('student');if(!ids.length)throw new Error('Pilih minimal satu siswa.');state.active=await result(db.rpc('create_class',{p_id:id,p_date:v.date,p_theme:v.theme,p_students:ids,p_duration:Number(v.duration)}));state.view='sessions';break;}
      case 'attendance':await result(db.rpc('save_attendance',{p_id:id,p_attendance:v.attendance}));break;
      case 'evaluation':{const targets=assessmentsFor(id);if(targets.length){const payload=targets.map(a=>({subject:a.subject,rating:v[`rating_${a.subject}`],note:v[`note_${a.subject}`]||''}));const observation={english_rating:v.english_rating||'',english_note:v.english_note||'',character_dimensions:f.getAll('character'),character_note:v.character_note||''};await result(db.rpc('finalize_competency_evaluation',{p_id:id,p_assessments:payload,p_anecdote:v.anecdote||'',p_observation:observation}));}else await result(db.rpc('finalize_evaluation',{p_id:id,p_grade:v.grade||null,p_anecdote:v.anecdote||''}));break;}
      case 'summative':await result(db.rpc('complete_summative',{p_student:id,p_score:Number(v.score),p_pass:v.pass==='true'}));break;
      case 'competency-targets':{for(const c of activeCompetenciesFor(id)){const target=Number(v[`target_${c.subject}`]);if(c.subject==='reading')await result(db.from('students').update({reading_target:target}).eq('id',id));else if(c.subject==='math')await result(db.from('students').update({math_target:target}).eq('id',id));else await result(db.from('student_competencies').update({target}).eq('student_id',id).eq('subject',c.subject));}break;}
      case 'member':await result(db.from('access_list').upsert({email:v.email.trim().toLowerCase(),name:v.name.trim(),role:'teacher',active:true},{onConflict:'email',ignoreDuplicates:true}));break;
      case 'assign':{const chosen=f.getAll('teacher');const old=state.assignments.filter(a=>a.student_id===id);for(const a of old.filter(a=>!chosen.includes(a.teacher_id)))await result(db.from('assignments').delete().eq('student_id',id).eq('teacher_id',a.teacher_id));for(const teacher_id of chosen.filter(t=>!old.some(a=>a.teacher_id===t)))await result(db.from('assignments').insert({student_id:id,teacher_id}));break;}
      case 'curriculum':{const payload={};for(const subject of subjects){payload[subject]=v[subject];payload[`${subject}_criteria`]=v[`${subject}_criteria`];}await result(db.from('curriculum').update(payload).eq('level',Number(id)));break;}
    }
    document.querySelector('#modal')?.close();await refresh();notify('Perubahan berhasil disimpan.');
  }catch(err){notify(err.message,true);}finally{buttons.forEach(b=>b.disabled=false);}
});
login();
if(db){db.auth.getSession().then(async({data})=>{if(data.session)try{await loadUser(data.session.user);}catch(err){notify(err.message,true);await db.auth.signOut();state.user=null;login();}});db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){state.user=null;state.demo=false;login();}});}
