import { createClient } from '@supabase/supabase-js';
import { escapeHtml as h, progress, waLink, localDate } from './domain.js';
import './style.css';

const ORG_NAME='Rumah Belajar Rainbow Kids Alfatih';

const root = document.querySelector('#app');
let publicConfig = {};
try { const response = await fetch(new URL('./config.json', location.href)); if (response.ok) publicConfig = await response.json(); } catch { /* Local preview is available without configuration. */ }
const url = import.meta.env.VITE_SUPABASE_URL || publicConfig.supabaseUrl;
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || publicConfig.supabasePublishableKey;
const configured = url?.startsWith('https://') && key && !url.includes('PROJECT_REF');
const db = configured ? createClient(url,key) : null;
const state = { user:null, role:'teacher', name:'', view:'dashboard', students:[], classes:[], records:[], alerts:[], members:[], assignments:[], profiles:[], themes:[], curriculum:[], active:null, demo:false, filter:'', onboarding:false };
let messageTimer;
const icons={dashboard:'◫',students:'◉',sessions:'▤',team:'♧',curriculum:'▥'};
const labels={dashboard:'Ringkasan',students:'Data siswa',sessions:'Ruang kelas',team:'Tim pengajar',curriculum:'Kurikulum'};
const field=(label,name,type='text',value='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${h(value)}" ${extra}></label>`;
const select=(label,name,items,value='',extra='')=>`<label>${label}<select name="${name}" ${extra}>${items.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${h(v)}" ${v===value?'selected':''}>${h(t)}</option>`;}).join('')}</select></label>`;
const area=(label,name,value='',extra='')=>`<label>${label}<textarea name="${name}" rows="3" ${extra}>${h(value)}</textarea></label>`;
const empty=(title,text)=>`<div class="empty"><span>✧</span><h3>${title}</h3><p>${text}</p></div>`;
const studentFor=r=>state.students.find(s=>s.id===r.student_id);
const ready=s=>s.reading_level>=s.reading_target&&s.math_level>=s.math_target;
function notify(text,error=false){ document.querySelector('.toast')?.remove(); const el=document.createElement('div');el.className=`toast ${error?'error':''}`;el.role='status';el.textContent=text;document.body.append(el);clearTimeout(messageTimer);messageTimer=setTimeout(()=>el.remove(),6500); }
async function result(query){ const {data,error}=await query;if(error)throw new Error(error.message);return data; }
async function allRows(table,order='id') { const rows=[]; for(let from=0;;from+=500){let query=db.from(table).select('*').order(order);if(table==='assignments')query=query.order('teacher_id');const page=await result(query.range(from,from+499));rows.push(...page);if(page.length<500)return rows;} }
function guardDemo(){if(state.demo)throw new Error('Ini pratinjau. Hubungkan Supabase dan masuk untuk menyimpan data.');}
async function refresh(){
  if(state.demo){render();return;}
  const [students,classes,records,themes,curriculum]=await Promise.all([
    allRows('students'),
    allRows('class_sessions'),
    allRows('session_students'),
    result(db.from('themes').select('*').order('name')),
    result(db.from('curriculum').select('*').order('level'))
  ]);
  students.sort((a,b)=>a.name.localeCompare(b.name)); classes.sort((a,b)=>b.date.localeCompare(a.date)||b.created_at.localeCompare(a.created_at));
  Object.assign(state,{students,classes,records,themes,curriculum});
  if(state.role==='owner'){
    [state.alerts,state.members,state.assignments,state.profiles]=await Promise.all([
      allRows('student_alerts','student_id'),allRows('access_list','email'),
      allRows('assignments','student_id'),allRows('profiles')
    ]);
  }
  render();
}
async function loadUser(user){
  state.user=user;state.demo=false;
  const profile=await result(db.from('profiles').select('*').eq('id',user.id).single());
  const member=await result(db.from('access_list').select('*').eq('email',profile.email).single());
  if(!member.active)throw new Error('Akses akun ini dinonaktifkan. Hubungi pemilik.');
  state.name=profile.name;state.role=member.role;state.onboarding=member.role==='teacher'&&localStorage.getItem('rb-onboarding-'+user.id)!=='1';await refresh();
}
function login(){
  root.innerHTML=`<main class="login"><section class="login-story"><div class="brand">b<span>·</span> ${ORG_NAME}</div><div><div class="eyebrow">RUANG TUMBUH BERSAMA</div><h1>Langkah kecil.<br><em>Kemajuan berarti.</em></h1><p>Lebih dekat dengan setiap anak.<br>Lebih tenang menjalani hari mengajar.</p><div class="story-card"><span class="sprout">✳</span><div><strong>Setiap anak punya jalannya.</strong><p>Materi personal · Evaluasi adaptif · Kabar baik untuk keluarga</p></div></div></div><small>Dibangun untuk guru yang peduli.</small></section><section class="login-form"><div class="login-box"><span class="pill">RUMAH BELAJAR / 02</span><h2>Selamat datang kembali</h2><p class="muted">Masuk untuk melanjutkan perjalanan belajar anak.</p>${!configured?'<div class="notice">Koneksi Supabase belum diatur. Pratinjau tampilan tersedia dengan data contoh.</div>':''}<form id="login-form">${field('Email terdaftar','email','email','','required autocomplete="email"')}${field('Kata sandi','password','password','','required minlength="8" autocomplete="current-password"')}<button class="primary full" ${configured?'':'disabled'}>Masuk ke ruang belajar →</button><button type="button" class="text-btn full" data-action="register" ${configured?'':'disabled'}>Aktivasi akun yang sudah didaftarkan pemilik</button></form><button class="secondary full" data-action="demo">Lihat pratinjau aplikasi</button><p class="fine">Akses hanya untuk pemilik dan guru terdaftar.</p></div></section></main>`;
}
function demo(){Object.assign(state,{demo:true,role:'owner',name:'Pemilik Bimbel',view:'dashboard',students:[
  {id:'demo-1',name:'Alya Putri',parent_name:'Bunda Rani',phone:'',interest:'Kupu-kupu & menggambar',reading_baseline:1,reading_level:4,reading_target:7,math_baseline:1,math_level:3,math_target:7,status:'Aktif',diagnostic:'Mengenali huruf vokal',learning_notes:'Senang belajar lewat gambar'},
  {id:'demo-2',name:'Bima Pratama',parent_name:'Ayah Danu',phone:'',interest:'Dinosaurus',reading_baseline:2,reading_level:3,reading_target:6,math_baseline:2,math_level:4,math_target:7,status:'Aktif'},
  {id:'demo-3',name:'Citra Kirana',parent_name:'Bunda Maya',phone:'',interest:'Cerita & hewan',reading_baseline:3,reading_level:7,reading_target:7,math_baseline:2,math_level:7,math_target:7,status:'Aktif'}
],classes:[],records:[],alerts:[{student_id:'demo-2',intervention:true,repeat_count:3}],members:[],assignments:[],profiles:[],themes:[{name:'Pasar'},{name:'Alam & Lingkungan'}],curriculum:[]});render();}
function render(){
  if(!state.user&&!state.demo){login();return;}
  const nav=state.role==='owner'?['dashboard','curriculum']:['dashboard','students','sessions','curriculum'];
  root.innerHTML=`<div class="shell"><aside class="sidebar"><a href="#" class="brand" data-view="dashboard">b<span>·</span><div>${ORG_NAME}<small>Ruang tumbuh bersama</small></div></a><div class="nav-label">RUANG KERJA</div><nav>${nav.map(k=>`<button class="nav-item ${state.view===k?'active':''}" data-view="${k}"><span aria-hidden="true">${icons[k]}</span>${labels[k]}${k==='sessions'?'<i>→</i>':''}</button>`).join('')}</nav><div class="sidebar-note"><span>✳</span><p>Setiap kemajuan<br>layak dirayakan.</p><small>Satu anak, satu perjalanan.</small></div><div class="account"><span class="avatar">${h(state.name.slice(0,1))}</span><div><strong>${h(state.name)}</strong><small>${state.role==='owner'?'Pemilik':'Guru pengajar'}</small></div><button title="Keluar" aria-label="Keluar" data-action="logout">↗</button></div></aside><main class="workspace"><header class="topbar"><span>${ORG_NAME} <span class="slash">/</span> ${labels[state.view]}</span><span class="date">${new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeZone:'Asia/Jakarta'}).format(new Date())}</span><div class="top-actions"><button data-action="refresh" title="Muat ulang data" aria-label="Muat ulang data">↻</button><button data-action="logout" aria-label="Keluar akun">Keluar ↗</button></div></header>${state.onboarding?'<div class="onboarding"><div><strong>Selamat datang, '+h(state.name)+'</strong><p>Mulai dari siswa yang ditugaskan, lalu buka sesi belajar saat siap.</p></div><button class="secondary" data-action="dismiss-onboarding">Mengerti</button></div>':''}${state.demo?'<div class="demo-banner">PRATINJAU · Data contoh, tidak tersimpan. <button data-action="logout">Kembali ke login →</button></div>':''}<section class="content">${({dashboard:dashboard,students:studentsView,sessions:sessionsView,team:teamView,curriculum:curriculumView})[state.view]()}</section><footer>${ORG_NAME} <span>Belajar bertumbuh, bersama.</span></footer></main></div><dialog id="modal"></dialog>`;
}
function heading(kicker,title,subtitle,button=''){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div>${button}</div>`;}
function ownerDashboard(){
  const active=state.students.filter(s=>s.status==='Aktif');
  const today=state.classes.filter(c=>c.date===localDate());
  const interventions=state.alerts.filter(a=>a.intervention);
  const sum=active.filter(ready);
  const pending=state.records.filter(r=>!r.finalized_at).length;
  const teachers=state.members.filter(m=>m.role==='teacher'&&m.active).length;
  return heading('PETA RUMAH BELAJAR','Halo, '+h(state.name.split(' ')[0])+' <span class="wave">✳</span>','Berikut hal penting yang membutuhkan perhatian Anda hari ini.','<button class="secondary" data-action="new-member">Kelola tim</button>')+
    '<div class="stats"><div class="stat"><span>Siswa aktif <i>◉</i></span><strong>'+active.length.toString().padStart(2,'0')+'</strong><small>Total perjalanan belajar</small></div><div class="stat"><span>Guru aktif <i>♧</i></span><strong>'+teachers.toString().padStart(2,'0')+'</strong><small>Tim yang mendampingi</small></div><div class="stat"><span>Sesi hari ini <i>▤</i></span><strong>'+today.length.toString().padStart(2,'0')+'</strong><small>Kelas yang berlangsung</small></div><div class="stat warm"><span>Perlu perhatian <i>♡</i></span><strong>'+interventions.length.toString().padStart(2,'0')+'</strong><small>Alarm untuk ditinjau</small></div></div>'+
    '<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><h2>Perlu keputusan</h2><p>Ringkasan pengecualian, bukan pekerjaan kelas.</p></div><span>✧</span></div>'+(interventions.length?interventions.map(a=>'<article class="attention-item"><span class="badge amber">Pendampingan khusus</span><h3>'+h(state.students.find(s=>s.id===a.student_id)?.name||'Siswa')+'</h3><p>Tiga kali mengulang di level yang sama. Tinjau bersama guru pendamping.</p></article>').join(''):'<article class="attention-item"><span class="badge green">Semua terkendali</span><h3>Tidak ada alarm intervensi</h3><p>Belum ada siswa yang membutuhkan keputusan khusus.</p></article>')+(sum.length?'<article class="attention-item"><span class="badge green">Siap sumatif</span><h3>'+sum.length+' siswa mencapai target</h3><p>Keputusan ujian sumatif dapat ditinjau saat diperlukan.</p></article>':'')+'</section><section class="panel"><div class="panel-heading"><div><h2>Ketertiban operasional</h2><p>Pemilik memantau; guru menyelesaikan.</p></div><span>◌</span></div><article class="attention-item"><span class="badge '+(pending?'amber':'green')+'">'+(pending?'Perlu ditinjau':'Rapi')+'</span><h3>'+(pending?pending+' sesi belum selesai dievaluasi':'Semua sesi sudah dievaluasi')+'</h3><p>Guru tetap menjadi pelaksana utama kegiatan kelas.</p></article></section></div>';
}
function dashboard(){
  if(state.role==='owner')return ownerDashboard();
  const active=state.students.filter(s=>s.status==='Aktif');const today=state.classes.filter(c=>c.date===localDate());const interventions=state.alerts.filter(a=>a.intervention);const sum=active.filter(ready);
  return `${heading('HARI BARU, KESEMPATAN BARU',`Halo, ${h(state.name.split(' ')[0])} <span class="wave">✳</span>`,'Mari temani langkah kecil yang berarti hari ini.','<button class="primary" data-action="new-session">＋ Mulai sesi kelas</button>')}<section class="welcome"><div><span class="pill light">BELAJAR SESUAI RITME ANAK</span><h2>Bukan siapa yang paling cepat.<br>Melainkan siapa yang terus bertumbuh.</h2><p>Kenali minatnya, dampingi prosesnya, rayakan kemajuannya.</p><button data-view="students">Lihat perjalanan siswa <span>↗</span></button></div><div class="growth-art" aria-hidden="true"><div class="orbit"></div><span class="petal p1"></span><span class="petal p2"></span><span class="petal p3"></span><span class="stem"></span><span class="art-label">TUMBUH DENGAN CARANYA</span></div></section><div class="stats"><div class="stat"><span>Siswa aktif <i>◉</i></span><strong>${active.length.toString().padStart(2,'0')}</strong><small>Perjalanan yang kita dampingi</small></div><div class="stat"><span>Sesi hari ini <i>▤</i></span><strong>${today.length.toString().padStart(2,'0')}</strong><small>Ruang untuk belajar bersama</small></div><div class="stat"><span>Siap ujian sumatif <i>✧</i></span><strong>${sum.length.toString().padStart(2,'0')}</strong><small>Target belajar sudah tercapai</small></div>${state.role==='owner'?`<div class="stat warm"><span>Butuh perhatian <i>♡</i></span><strong>${interventions.length.toString().padStart(2,'0')}</strong><small>Mari dampingi lebih dekat</small></div>`:''}</div><div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Perjalanan belajar</h2><button class="text-btn" data-view="students">Semua siswa →</button></div>${active.length?active.slice(0,5).map(studentRow).join(''):empty('Perjalanan dimulai di sini','Tambahkan siswa pertama untuk mulai mendampingi belajarnya.')}</section><section class="panel attention"><div class="panel-heading"><h2>Catatan untuk Anda</h2><span>✧</span></div>${state.role==='owner'&&interventions.length?interventions.map(a=>`<article class="attention-item"><span class="badge amber">Pendampingan khusus</span><h3>${h(state.students.find(s=>s.id===a.student_id)?.name)}</h3><p>Tiga kali mengulang di level yang sama. Tinjau pendekatan belajar dan diskusikan dengan guru.</p></article>`).join(''):'<article class="attention-item"><span class="badge green">Langkah hari ini</span><h3>Mulai dari rasa ingin tahu</h3><p>Gunakan minat anak sebagai pintu masuk sebelum mengenalkan tantangan baru.</p></article>'}${sum.length?`<article class="attention-item"><span class="badge green">Siap sumatif</span><h3>${sum.length} siswa mencapai target</h3><p>Buka profil siswa untuk mencatat hasil ujian akhir.</p></article>`:''}<div class="quote">“Kemajuan kecil tetaplah kemajuan.”<small>Pengingat untuk hari ini</small></div></section></div>`;
}
function studentRow(s){return `<button class="student-row" data-action="student" data-id="${s.id}"><span class="avatar pastel">${h(s.name[0])}</span><div class="student-info"><strong>${h(s.name)}</strong><small>${h(s.interest||'Minat belum diisi')}</small></div><div class="mini-progress"><small>Membaca <b>${s.reading_level}/${s.reading_target}</b></small><progress value="${progress(s.reading_level,s.reading_baseline,s.reading_target)}" max="100"></progress></div><span class="row-arrow">↗</span></button>`;}
function studentsView(){const list=state.students.filter(s=>s.name.toLowerCase().includes(state.filter.toLowerCase()));return `${heading('SETIAP ANAK UNIK','Kenali, lalu dampingi.','Profil, minat, dan perjalanan kompetensi setiap anak.',state.role==='owner'||state.role==='teacher'?'<button class="primary" data-action="new-student">＋ Tambah siswa</button>':'')}<div class="toolbar"><input id="student-search" type="search" placeholder="Cari nama siswa…" aria-label="Cari siswa" value="${h(state.filter)}"><span>${state.students.length} siswa terdaftar</span></div><div class="student-grid">${list.map(s=>`<article class="panel student-card"><div class="card-top"><span class="avatar large">${h(s.name[0])}</span><span class="badge ${ready(s)?'amber':'green'}">${h(s.status)}${ready(s)&&s.status==='Aktif'?' · Siap sumatif':''}</span></div><h2>${h(s.name)}</h2><p>${h(s.interest||'Minat belum diisi')}</p>${meter('Membaca',s.reading_level,s.reading_baseline,s.reading_target)}${meter('Berhitung',s.math_level,s.math_baseline,s.math_target)}<button class="secondary full" data-action="student" data-id="${s.id}">Lihat profil & riwayat ↗</button></article>`).join('')||empty('Belum ada siswa','Data siswa yang ditugaskan kepada Anda akan tampil di sini.')}</div>`;}
function meter(label,current,baseline,target){return `<div class="meter"><div><span>${label}</span><strong>Level ${current} <small>/ ${target}</small></strong></div><progress value="${progress(current,baseline,target)}" max="100"></progress><small>Mulai level ${baseline} · ${progress(current,baseline,target)}% menuju target</small></div>`;}
function sessionsView(){
  const c=state.classes.find(c=>c.id===state.active);
  if(c)return `${heading('SATU RUANG, SEMUA KEBUTUHAN',h(c.theme),`${h(c.date)} · ${state.records.filter(r=>r.session_id===c.id).length} siswa`,'<button class="secondary" data-action="back-sessions">← Semua sesi</button>')}<div class="notice">Urutan mengajar: simpan kehadiran → buat panduan → dampingi anak → simpan evaluasi di akhir kelas → buat dan periksa rapor.</div><div class="session-list">${state.records.filter(r=>r.session_id===c.id).map(recordCard).join('')}</div>`;
  return `${heading('RUANG KELAS','Siap belajar bersama?','Satu sesi, materi sesuai level dan minat masing-masing anak.','<button class="primary" data-action="new-session">＋ Mulai sesi kelas</button>')}<div class="panel">${state.classes.map(c=>{const rr=state.records.filter(r=>r.session_id===c.id);return `<button class="class-row" data-action="open-session" data-id="${c.id}"><span class="calendar">${h(c.date.slice(8))}<small>${h(c.date.slice(0,7))}</small></span><div><h3>${h(c.theme)}</h3><p>${rr.length} siswa · ${rr.filter(r=>r.finalized_at).length} evaluasi selesai</p></div><span>Masuk kelas →</span></button>`;}).join('')||empty('Ruang kelas menanti','Pilih siswa dan tema untuk membuka sesi pertama.')}</div>`;
}
function recordCard(r){const s=studentFor(r);if(!s)return '';const link=waLink(s.phone,r.report);return `<article class="panel session-card"><div class="panel-heading"><div><h2>${h(s.name)}</h2><p>${h(s.interest)} · Membaca ${r.reading_snapshot} · Berhitung ${r.math_snapshot}</p></div><span class="badge ${r.finalized_at?'green':'amber'}">${r.finalized_at?'Evaluasi tersimpan':'Sesi berlangsung'}</span></div><form data-form="attendance" data-id="${r.id}" class="inline-form">${select('Kehadiran','attendance',['Hadir','Sakit','Izin','Alfa'],r.attendance,r.finalized_at?'disabled':'')}<button class="secondary" ${r.finalized_at?'disabled':''}>Simpan kehadiran</button></form>${r.attendance==='Hadir'?`<section class="lesson"><div class="section-title"><h3>01 / Panduan mengajar</h3><button class="secondary" data-action="generate" data-kind="material" data-id="${r.id}">${r.material?'Lihat panduan tersimpan':'✧ Buat panduan AI'}</button></div>${r.material?`<pre>${h(r.material)}</pre><button class="text-btn" data-action="print" data-id="${r.id}">Cetak panduan (opsional)</button>`:'<p class="muted">Panduan mencakup membaca, menulis, berhitung, bahasa Inggris, dan karakter.</p>'}</section>`:''}<form data-form="evaluation" data-id="${r.id}" class="evaluation"><h3>02 / Evaluasi akhir kelas</h3>${r.attendance==='Hadir'?select('Perkembangan hari ini','grade',[['','Pilih penilaian'],['SB','SB — Sangat Baik'],['BSH','BSH — Berkembang Sesuai Harapan'],['MB','MB — Mulai Berkembang']],r.grade||'',r.finalized_at?'disabled':'required'):''}${area('Catatan anekdot (opsional)','anecdote',r.anecdote,`maxlength="3000" ${r.finalized_at?'disabled':''}`)}<button class="primary" ${r.finalized_at?'disabled':''}>${r.finalized_at?'✓ Evaluasi sudah tersimpan':'Simpan & selesaikan evaluasi'}</button><small class="fine">Nilai tersimpan satu kali. SB/BSH menaikkan level; MB memberi kesempatan latihan kembali.</small></form><section class="report"><div class="section-title"><h3>03 / Kabar untuk orang tua</h3>${r.attendance==='Hadir'?`<button class="secondary" data-action="generate" data-kind="report" data-id="${r.id}" ${!r.finalized_at?'disabled':''}>${r.report?'Lihat rapor tersimpan':'✧ Buat draf rapor'}</button>`:''}</div>${r.report?`<pre>${h(r.report)}</pre><div class="button-row"><button class="secondary" data-action="copy" data-id="${r.id}">Salin pesan</button>${link?`<a class="primary" target="_blank" rel="noopener noreferrer" href="${h(link)}">Periksa & buka WhatsApp ↗</a>`:'<small>Lengkapi nomor WhatsApp di profil siswa untuk membuka percakapan.</small>'}</div>`:'<p class="muted">Rapor dibuat setelah evaluasi agar kabarnya sesuai kegiatan nyata.</p>'}</section></article>`;}
function teamView(){return `${heading('TIM YANG SALING MENDUKUNG','Guru yang mendampingi.','Daftarkan email guru, lalu tugaskan siswa yang dapat mereka akses.','<button class="primary" data-action="new-member">＋ Daftarkan guru</button>')}<div class="panel">${state.members.map(m=>`<div class="class-row"><span class="avatar">${h(m.name[0])}</span><div><h3>${h(m.name)}</h3><p>${h(m.email)} · ${m.role==='owner'?'Pemilik':'Guru'} · ${m.active?'Aktif':'Nonaktif'}</p></div>${m.role==='teacher'?`<button class="secondary" data-action="toggle-member" data-id="${h(m.email)}">${m.active?'Nonaktifkan':'Aktifkan'}</button>`:''}</div>`).join('')||empty('Belum ada guru','Tambahkan email guru. Guru kemudian mengaktifkan akun melalui halaman login.')}</div><div class="notice">Guru mengaktifkan akun menggunakan email yang didaftarkan di sini. Penugasan siswa tersedia di profil siswa setelah guru mengaktifkan akun.</div>`;}
function curriculumView(){return `${heading('TANGGA KOMPETENSI','Bertumbuh, satu level sekali.','Bank instruksi dasar untuk menjaga ketepatan materi dan menghemat penggunaan AI.')}<div class="curriculum-grid">${state.curriculum.map(c=>`<article class="panel"><span class="badge green">LEVEL ${c.level}</span><h2>${c.level<=2?'TK A':c.level<=4?'TK B':c.level<=6?'SD 1':c.level<=8?'SD 2':c.level<=10?'SD 3':c.level<=12?'SD 4':c.level<=14?'SD 5':'SD 6'}</h2>${['reading','writing','math','english','character'].map((k,i)=>`<p><strong>${['Membaca','Menulis','Berhitung','Inggris','Karakter'][i]}</strong><br>${h(c[k])}</p>`).join('')}${state.role==='owner'?`<button class="secondary" data-action="edit-curriculum" data-id="${c.level}">Edit instruksi dasar</button>`:''}</article>`).join('')||empty('Bank kurikulum','Sepuluh level kurikulum akan tersedia setelah database terhubung.')}</div>`;}
function modal(title,body){const d=document.querySelector('#modal');d.innerHTML=`<div class="modal-head"><h2>${title}</h2><button data-action="close" aria-label="Tutup">✕</button></div>${body}`;d.showModal();}
function studentForm(s={}){const owner=state.role==='owner';const canCreate=owner||state.role==='teacher';const edit=!!s.id;modal(edit?h(s.name):'Siswa baru',`<form data-form="student" data-id="${s.id||''}"><fieldset ${canCreate?'':'disabled'}><div class="form-grid">${field('Nama anak','name','text',s.name,'required maxlength="120"')}${field('Sapaan orang tua','parent_name','text',s.parent_name,'required maxlength="120"')}${field('Nomor WhatsApp','phone','tel',s.phone)}${field('Minat / hobi','interest','text',s.interest,'required maxlength="300"')}</div>${area('Hasil diagnostik awal','diagnostic',s.diagnostic,'maxlength="3000"')}${area('Catatan gaya belajar','learning_notes',s.learning_notes,'maxlength="3000"')}<div class="form-grid">${field(edit?'Level awal membaca (terkunci)':'Level awal membaca','reading_baseline','number',s.reading_baseline||1,`min="1" max="16" required ${edit?'disabled':''}`)}${field('Target membaca','reading_target','number',s.reading_target||7,'min="1" max="16" required')}${field(edit?'Level awal berhitung (terkunci)':'Level awal berhitung','math_baseline','number',s.math_baseline||1,`min="1" max="16" required ${edit?'disabled':''}`)}${field('Target berhitung','math_target','number',s.math_target||7,'min="1" max="16" required')}</div>${edit?select('Status','status',s.status==='Lulus'?['Lulus','Non-Aktif']:['Aktif','Non-Aktif'],s.status):''}</fieldset>${canCreate?'<button class="primary full">Simpan profil siswa</button>':''}</form>${edit?`<hr>${meter('Membaca',s.reading_level,s.reading_baseline,s.reading_target)}${meter('Berhitung',s.math_level,s.math_baseline,s.math_target)}${owner?`<form data-form="assign" data-id="${s.id}"><h3>Guru pendamping</h3>${state.profiles.filter(p=>state.members.some(m=>m.email===p.email&&m.role==='teacher'&&m.active)).map(p=>`<label class="check"><input type="checkbox" name="teacher" value="${p.id}" ${state.assignments.some(a=>a.student_id===s.id&&a.teacher_id===p.id)?'checked':''}>${h(p.name)}</label>`).join('')||'<p>Belum ada guru yang mengaktifkan akun.</p>'}<button class="secondary">Simpan penugasan</button></form>`:''}${owner&&ready(s)&&s.status==='Aktif'?`<hr><form data-form="summative" data-id="${s.id}"><h3>Ujian sumatif akhir</h3>${field('Nilai akhir (1–100)','score','number',s.summative_score||'','required min="1" max="100"')}${select('Keputusan pemilik','pass',[['false','Perlu pendampingan lanjutan'],['true','Lulus']], 'false')}<button class="primary">Simpan hasil sumatif</button></form>`:''}<hr><h3>Riwayat evaluasi</h3>${state.records.filter(r=>r.student_id===s.id&&r.finalized_at).sort((a,b)=>b.finalized_at.localeCompare(a.finalized_at)).map(r=>`<p class="history">${h(state.classes.find(c=>c.id===r.session_id)?.date||r.finalized_at.slice(0,10))} · ${h(r.attendance)} · <strong>${h(r.grade||'Tanpa nilai')}</strong><br><small>${h(r.anecdote)}</small></p>`).join('')||'<p class="muted">Belum ada evaluasi tersimpan.</p>'}`:''}`);}
function newSession(){const available=state.students.filter(s=>s.status==='Aktif'&&!state.records.some(r=>r.student_id===s.id&&!r.finalized_at));modal('Mulai sesi kelas',`<form data-form="session" data-id="${crypto.randomUUID()}">${field('Tanggal','date','date',localDate(),'required')}${field('Tema bersama','theme','text',state.themes[0]?.name||'','required maxlength="120" list="themes"')}<datalist id="themes">${state.themes.map(t=>`<option value="${h(t.name)}">`).join('')}</datalist><h3>Pilih anak yang mengikuti sesi</h3>${available.map(s=>`<label class="check"><input type="checkbox" name="student" value="${s.id}">${h(s.name)} <small>Membaca ${s.reading_level} · Berhitung ${s.math_level}</small></label>`).join('')||'<p>Belum ada siswa tersedia. Tambahkan siswa atau selesaikan sesi yang masih terbuka.</p>'}<button class="primary full" ${available.length?'':'disabled'}>Buka ruang kelas →</button></form>`);}
document.addEventListener('click',async e=>{
  const b=e.target.closest('[data-action],[data-view]');if(!b)return;e.preventDefault();
  if(b.dataset.view){state.view=b.dataset.view;state.active=null;render();return;}
  const {action,id,kind}=b.dataset;
  try{
    if(action==='demo')return demo();
    if(action==='dismiss-onboarding'){localStorage.setItem('rb-onboarding-'+state.user.id,'1');state.onboarding=false;return render();}
    if(action==='refresh'){await refresh();return notify('Data terbaru sudah dimuat.');}
    if(action==='logout'){if(db&&!state.demo)await db.auth.signOut();Object.assign(state,{user:null,demo:false,students:[],records:[],alerts:[],members:[]});return login();}
    if(action==='close')return document.querySelector('#modal').close();
    if(action==='student')return studentForm(state.students.find(s=>s.id===id));
    if(action==='new-student')return studentForm();
    if(action==='new-session')return newSession();
    if(action==='open-session'){state.active=id;return render();}
    if(action==='back-sessions'){state.active=null;return render();}
    if(action==='new-member')return modal('Daftarkan guru',`<form data-form="member">${field('Nama guru','name','text','','required maxlength="120"')}${field('Email guru','email','email','','required')}<button class="primary full">Daftarkan email guru</button></form>`);
    if(action==='edit-curriculum'){const c=state.curriculum.find(c=>c.level===Number(id));return modal(`Kurikulum level ${id}`,`<form data-form="curriculum" data-id="${id}">${['reading','writing','math','english','character'].map((k,i)=>area(['Membaca','Menulis','Berhitung','Inggris','Karakter'][i],k,c[k],'required maxlength="2000"')).join('')}<button class="primary">Simpan kurikulum</button></form>`);}
    if(action==='copy'){await navigator.clipboard.writeText(state.records.find(r=>r.id===id).report);return notify('Pesan berhasil disalin.');}
    if(action==='print'){document.querySelectorAll('.session-card').forEach(el=>el.classList.toggle('print-target',!!el.querySelector(`[data-id="${id}"]`)));return window.print();}
    guardDemo();b.disabled=true;
    if(action==='register'){const form=document.querySelector('#login-form');if(!form.reportValidity())return;const f=new FormData(form);await result(db.auth.signUp({email:f.get('email'),password:f.get('password'),options:{emailRedirectTo:location.origin+location.pathname}}));notify('Aktivasi diterima. Periksa email konfirmasi, lalu masuk.');}
    if(action==='toggle-member'){const m=state.members.find(m=>m.email===id);await result(db.from('access_list').update({active:!m.active}).eq('email',id));await refresh();}
    if(action==='generate'){const r=state.records.find(r=>r.id===id);if(r[kind==='material'?'material':'report'])return notify('Hasil tersimpan sudah tampil di kartu ini.');b.textContent='Sedang menyusun…';const {data,error}=await db.functions.invoke('generate-learning',{body:{record_id:id,kind}});if(error){let detail;try{detail=await error.context?.json();}catch{}throw new Error(detail?.error||error.message);}if(data?.error)throw new Error(data.error);await refresh();notify('Hasil AI tersimpan. Periksa isinya sebelum digunakan.');}
  }catch(err){notify(err.message,true);}finally{b.disabled=false;}
});
document.addEventListener('input',e=>{if(e.target.id==='student-search'){state.filter=e.target.value;const pos=e.target.selectionStart;render();const input=document.querySelector('#student-search');input.focus();try{input.setSelectionRange(pos,pos);}catch{}}});
document.addEventListener('submit',async e=>{
  e.preventDefault();const form=e.target;const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);
  try{
    guardDemo();const f=new FormData(form);const v=Object.fromEntries(f);const id=form.dataset.id;
    if(form.id==='login-form'){const data=await result(db.auth.signInWithPassword({email:v.email,password:v.password}));await loadUser(data.user);return;}
    switch(form.dataset.form){
      case 'student':{const payload={name:v.name.trim(),parent_name:v.parent_name.trim(),phone:v.phone,interest:v.interest,diagnostic:v.diagnostic,learning_notes:v.learning_notes,reading_target:Number(v.reading_target),math_target:Number(v.math_target)};if(id){payload.status=v.status;await result(db.from('students').update(payload).eq('id',id));}else{Object.assign(payload,{reading_baseline:Number(v.reading_baseline),math_baseline:Number(v.math_baseline)});if(state.role==='owner'){Object.assign(payload,{reading_level:payload.reading_baseline,math_level:payload.math_baseline});await result(db.from('students').insert(payload));}else await result(db.rpc('create_student',{p_payload:payload}));}break;}
      case 'session':{const ids=f.getAll('student');if(!ids.length)throw new Error('Pilih minimal satu siswa.');state.active=await result(db.rpc('create_class',{p_id:id,p_date:v.date,p_theme:v.theme,p_students:ids}));state.view='sessions';break;}
      case 'attendance':await result(db.rpc('save_attendance',{p_id:id,p_attendance:v.attendance}));break;
      case 'evaluation':await result(db.rpc('finalize_evaluation',{p_id:id,p_grade:v.grade||null,p_anecdote:v.anecdote||''}));break;
      case 'summative':await result(db.rpc('complete_summative',{p_student:id,p_score:Number(v.score),p_pass:v.pass==='true'}));break;
      case 'member':await result(db.from('access_list').upsert({email:v.email.trim().toLowerCase(),name:v.name.trim(),role:'teacher',active:true},{onConflict:'email',ignoreDuplicates:true}));break;
      case 'assign':{const chosen=f.getAll('teacher');const old=state.assignments.filter(a=>a.student_id===id);for(const a of old.filter(a=>!chosen.includes(a.teacher_id)))await result(db.from('assignments').delete().eq('student_id',id).eq('teacher_id',a.teacher_id));for(const teacher_id of chosen.filter(t=>!old.some(a=>a.teacher_id===t)))await result(db.from('assignments').insert({student_id:id,teacher_id}));break;}
      case 'curriculum':await result(db.from('curriculum').update(v).eq('level',Number(id)));break;
    }
    document.querySelector('#modal')?.close();await refresh();notify('Perubahan berhasil disimpan.');
  }catch(err){notify(err.message,true);}finally{buttons.forEach(b=>b.disabled=false);}
});
login();
if(db){db.auth.getSession().then(async({data})=>{if(data.session)try{await loadUser(data.session.user);}catch(err){notify(err.message,true);await db.auth.signOut();state.user=null;login();}});db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){state.user=null;state.demo=false;login();}});}
