-- Data kurikulum L9–L18 (SD kelas 2–6): level, tema, subtema, indikator.
-- Dihasilkan dari docs/curriculum/indikator/alur-*-l9-l18.md yang dikunci Sep 2026.
-- Tema 9–16 adalah konten sementara (siklus 2); diganti konten SD asli saat tersedia.
-- Jangan disunting tangan — perubahan lewat dokumen lalu migrasi baru.

-- 1. Level L9–L18

insert into public.k8_levels(level, title, description) values
  (9,  'Kelancaran Berimbuhan',   'Anak membaca akurat kata berimbuhan awalan dan akhiran, memahami kalimat majemuk sederhana, menghitung bilangan 3 digit, menulis kalimat dari gagasan sendiri, dan mengenali bangun datar. Level ini cocok untuk awal kelas 2 SD (Fase A lanjut).'),
  (10, 'Kosakata dan Operasi',    'Anak membaca kata berakhiran, mengenali hubungan makna, mengoperasikan perkalian dan pembagian dasar, menyalin dari jarak, dan membaca jam. Level ini cocok untuk akhir kelas 2 SD.'),
  (11, 'Paragraf dan Perkalian',  'Anak membaca paragraf informasi, mengenali kalimat majemuk, mengubah kalimat aktif-pasif, menghitung perkalian 2×1 digit, dan menulis paragraf dengan gagasan pokok. Level ini cocok untuk awal kelas 3 SD (Fase B).'),
  (12, 'Narasi dan Pecahan',      'Anak membaca narasi berurutan, menentukan gagasan pokok, menyusun urutan kalimat, mengoperasikan pecahan berpenyebut sama, dan menulis narasi pendek. Level ini cocok untuk akhir kelas 3 SD.'),
  (13, 'Analisis Teks Dasar',     'Anak mengenali cara pengembangan paragraf, membaca kosakata akademik dari konteks, menghitung perkalian 2×2 digit dan volume kubus/balok, serta menulis paragraf deskripsi. Level ini cocok untuk awal kelas 4 SD.'),
  (14, 'Penulisan Formal',        'Anak membedakan fakta dari opini, membaca kalimat majemuk kompleks, memilih diksi formal, mengoperasikan desimal, dan menulis teks informasi dari kerangka. Level ini cocok untuk akhir kelas 4 SD.'),
  (15, 'Argumentasi Awal',        'Anak menganalisis struktur argumentasi, membaca dengan prediksi isi, menyusun paragraf argumentasi, menghitung bilangan bulat negatif dan luas segitiga. Level ini cocok untuk awal kelas 5 SD (Fase C).'),
  (16, 'Teks Ilmiah Populer',     'Anak menentukan kosakata akademik dari konteks ilmiah, membaca dengan strategi menemukan informasi kunci, menggunakan kosakata akademik dalam kalimat, menghitung perbandingan dan keliling lingkaran. Level ini cocok untuk akhir kelas 5 SD.'),
  (17, 'Analisis Sudut Pandang',  'Anak menganalisis perangkat kohesi leksikal, mengidentifikasi sudut pandang penulis, merevisi kalimat, menghitung operasi campuran bilangan bulat dan luas trapesium. Level ini cocok untuk awal kelas 6 SD.'),
  (18, 'Produksi Teks Mandiri',   'Anak mengevaluasi koherensi paragraf, membaca dua sudut pandang berbeda, menyusun teks argumentasi dengan klaim-argumen-simpulan, menghitung mean/median/modus. Level ini adalah sasaran akhir kurikulum 18 level, setara akhir kelas 6 SD.');

-- 2. Tema 9–16 (siklus 2, konten sementara — pertemuan 193–384)

insert into public.k8_themes(number, name, first_meeting, last_meeting, description, objects, vocabulary, character, illustration) values
  (9,  'Rumah dan Kebiasaan Harian [Siklus 2]', 193, 216,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini memakai benda dan rutinitas rumah sebagai konteks bersama untuk berbicara, menghitung, mengelompokkan, mengukur, menulis, dan membangun kebiasaan rapi.',
   'kain serbet polos, sapu kecil, wadah plastik, kotak penyimpanan, sandal bersih, gantungan baju, bantal kecil, botol kosong polos, tutup botol, cangkir polos.',
   'rumah, ruang, bersih, rapi, simpan, ambil, letak, pagi, sore, kebiasaan, tempat, bantu.',
   'salam saat datang, doa sebelum belajar, mengucapkan terima kasih saat menerima alat, menunggu giliran memakai benda, dan merapikan alat setelah kegiatan.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 2–3 saat ini.'),
  (10, 'Pasar dan Warung [Siklus 2]', 217, 240,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini memakai suasana pasar kecil dan warung sebagai konteks benda nyata yang mudah dihitung, dibandingkan, dikelompokkan, dan diceritakan.',
   'wortel, tomat, mentimun, jeruk, pisang, salak, keranjang kecil, kantong kain polos, wadah bening polos, karet gelang, tutup wadah, uang mainan polos tanpa angka.',
   'pasar, warung, sayur, buah, keranjang, pilih, banyak, sedikit, panjang, pendek, kelompok, jual.',
   'antre saat memilih benda, berterima kasih setelah menerima benda, jujur saat menyatakan tugas sudah/belum selesai, dan merapikan dagangan main.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 2–3 saat ini.'),
  (11, 'Kebun dan Tanaman [Siklus 2]', 241, 264,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini menghadirkan tanaman, biji, dan alat kebun sederhana sebagai konteks konkret untuk mengamati ciri benda, pola, urutan, ukuran, dan perubahan.',
   'daun, ranting, biji kacang hijau, kapas tanam, batu kecil, tali rafia, sekop plastik, penyiram kecil kosong, nampan, wadah tanah kering tertutup.',
   'kebun, tanaman, daun, biji, tunas, tumbuh, rawat, kering, basah, urut, ukur, siram.',
   'meminta izin memakai alat, menunggu giliran menyentuh bahan, berterima kasih saat dibantu, menjaga kebersihan, dan mengembalikan alat ke tempatnya.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 3–4 saat ini.'),
  (12, 'Dapur dan Makanan Sehat [Siklus 2]', 265, 288,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini memakai alat makan dan bahan makanan nyata sebagai konteks untuk bahasa, bilangan, kategori, ukuran, dan adab sebelum/sesudah kegiatan.',
   'piring plastik, mangkuk plastik, sendok, nampan, serbet polos, wortel, kentang, jagung, buncis, botol kosong polos, spons bersih.',
   'dapur, sehat, piring, mangkuk, nampan, sayur, rasa, lembut, keras, hangat, dingin, siapkan.',
   'doa sebelum belajar, berbagi alat, menunggu giliran, meminta maaf dalam main peran ringan, dan merapikan meja.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 3–4 saat ini.'),
  (13, 'Kendaraan dan Jalan [Siklus 2]', 289, 312,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini memakai kendaraan mainan polos dan jalur sederhana untuk konteks urutan, posisi, sebab-akibat, bilangan, pola, dan cerita.',
   'mobil mainan polos, truk mainan polos, tali sebagai jalan, balok sebagai jembatan, tutup botol sebagai roda, kain sebagai jalan, kotak sebagai garasi, stik polos, helm mainan polos.',
   'jalan, kendaraan, maju, berhenti, belok, dekat, jauh, jembatan, garasi, cepat, pelan, perjalanan.',
   'menunggu giliran menjalankan kendaraan, meminta maaf dalam main peran tabrakan kecil, jujur saat tugas selesai/belum, dan merapikan jalur.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 4–5 saat ini.'),
  (14, 'Masjid dan Adab Harian [Siklus 2]', 313, 336,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini memakai benda dan rutinitas adab harian yang dekat dengan identitas bimbel Islami, tanpa menilai keimanan atau praktik keluarga.',
   'sajadah kecil polos, peci, sarung kecil, mukena anak, sandal bersih, kain penutup, kotak polos, botol kosong polos, wadah alat.',
   'salam, doa, bersih, rapi, giliran, bantu, maaf, terima kasih, simpan, hormat, tenang, bersama.',
   'salam Islami, doa pendek sebelum belajar, menunggu giliran, mengucapkan terima kasih, merapikan alat, dan main peran meminta maaf.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 4–5 saat ini.'),
  (15, 'Alam dan Cuaca [Siklus 2]', 337, 360,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini memakai benda alam sekitar dan kondisi cuaca sederhana sebagai konteks untuk mengamati, membandingkan, mengurutkan, mengukur, dan memahami sebab-akibat.',
   'payung kecil polos, kain kering, kain lembap, kipas tangan polos, daun kering, batu kecil, ranting, wadah bening kosong, ember kecil polos, tali, penjepit, kapas, nampan.',
   'alam, cuaca, panas, teduh, hujan, kering, lembap, angin, bergerak, jatuh, ringan, berat.',
   'membantu mengambil benda yang jatuh, berterima kasih, menunggu giliran memakai kipas, menyatakan tugas sudah/belum selesai, dan merapikan bahan alam.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 5–6 saat ini.'),
  (16, 'Tubuh Sehat dan Gerak [Siklus 2]', 361, 384,
   '[Siklus 2 — konten sementara; diganti konten SD kelas 2–6 saat tersedia.] Tema ini memakai alat kebersihan diri, gerak sederhana, dan rutinitas sehat sebagai konteks konkret untuk bahasa, urutan, ukuran, dan kemandirian.',
   'sikat gigi baru tertutup, handuk kecil, sisir, sabun kemasan polos atau ditutup, botol kosong polos, pita gerak, bola kecil polos, matras kecil, wadah alat, kain penanda tempat.',
   'sehat, gerak, lompat, duduk, berdiri, cuci, bersih, istirahat, kuat, lelah, rapi, rutinitas.',
   'menjalankan rutinitas pendek, merapikan alat, menunggu giliran gerak, meminta maaf dalam main peran ringan, dan berterima kasih setelah dibantu.',
   'Konten siklus 2 belum tersedia. Guru menggunakan bahan dan konteks yang sesuai dengan level SD kelas 5–6 saat ini.');

-- 3. Subtema 9–16 (pertemuan = siklus 1 + 192)

insert into public.k8_subthemes(theme, position, name, first_meeting, last_meeting) values
  (9,  1, 'Ruang di rumah',             193, 198),
  (9,  2, 'Alat kebersihan',            199, 204),
  (9,  3, 'Kegiatan pagi',              205, 210),
  (9,  4, 'Kegiatan sore',              211, 216),
  (10, 1, 'Sayur di pasar',             217, 222),
  (10, 2, 'Buah lokal',                 223, 228),
  (10, 3, 'Wadah dan kantong',          229, 234),
  (10, 4, 'Menata dagangan',            235, 240),
  (11, 1, 'Bagian tanaman',             241, 246),
  (11, 2, 'Biji dan tunas',             247, 252),
  (11, 3, 'Alat berkebun',              253, 258),
  (11, 4, 'Merawat kebun',              259, 264),
  (12, 1, 'Alat makan',                 265, 270),
  (12, 2, 'Bahan sayur',                271, 276),
  (12, 3, 'Rasa dan tekstur',           277, 282),
  (12, 4, 'Menyiapkan meja',            283, 288),
  (13, 1, 'Kendaraan darat',            289, 294),
  (13, 2, 'Jalan dan jembatan',         295, 300),
  (13, 3, 'Tanda jalan buatan guru',    301, 306),
  (13, 4, 'Perjalanan singkat',         307, 312),
  (14, 1, 'Salam dan masuk ruangan',    313, 318),
  (14, 2, 'Bersih dan rapi',            319, 324),
  (14, 3, 'Perlengkapan ibadah',        325, 330),
  (14, 4, 'Berbagi dan bergiliran',     331, 336),
  (15, 1, 'Panas dan teduh',            337, 342),
  (15, 2, 'Hujan dan kering',           343, 348),
  (15, 3, 'Angin dan gerak',            349, 354),
  (15, 4, 'Benda alam sekitar',         355, 360),
  (16, 1, 'Gerak tubuh',                361, 366),
  (16, 2, 'Alat kebersihan diri',       367, 372),
  (16, 3, 'Istirahat dan tenaga',       373, 378),
  (16, 4, 'Rutinitas sehat',            379, 384);

-- 4. Indikator L9–L18 (140 baris; slot urut A1 B1 E1 D1 C1 F1 A2 B2 E2 D2 C2 F2 EN KR)

insert into public.k8_indicators(level, number, slot, competency, method, material, success) values

-- ── L9 ──────────────────────────────────────────────────────────────────────
(9, 1, 'A1',
 'Membaca akurat kata berawalan me- dan ber-.',
 'Guru berkata: "Baca kata-kata ini satu per satu dengan suara jelas."',
 'membaca, menulis, melihat, membawa, membuka, berlari, bermain, belajar, berbicara, bekerja',
 'Minimal 8 dari 10 kata dibaca benar tanpa mengeja huruf per huruf.'),
(9, 2, 'B1',
 'Menentukan arti kata dari konteks kalimat sederhana.',
 'Guru membacakan empat kalimat. Setelah tiap kalimat, tanyakan arti kata sasaran.',
 '"Rina teliti saat menghitung." Apa arti teliti? "Budi lega setelah tugasnya selesai." Apa arti lega? "Kelas itu rapi." Apa arti rapi? "Dina hemat memakai uang jajan." Apa arti hemat?',
 '3 dari 4 tepat. Kunci/padanan: cermat; tenang/senang karena selesai; tertata; tidak boros.'),
(9, 3, 'E1',
 'Menentukan nilai tempat ratusan, puluhan, dan satuan pada bilangan cacah 3 digit.',
 'Guru berkata: "Bacalah bilangan ini. Lalu sebutkan angka ratusan, puluhan, dan satuannya."',
 '236, 408, 751, 690, 125',
 '4 dari 5 bilangan diuraikan benar.'),
(9, 4, 'D1',
 'Menyalin satu paragraf pendek dari model visual dekat dengan ejaan sesuai model.',
 'Guru menulis paragraf 4 kalimat, 35–45 kata, di kertas yang diletakkan ±30 cm dari anak. Guru berkata: "Salin paragraf ini sama seperti contoh."',
 'Paragraf tentang kegiatan sehari-hari; model tetap terlihat.',
 'Semua kalimat tersalin urut; tidak ada kalimat hilang; ≤3 kesalahan ejaan/salin; ≤2 kesalahan kapital atau tanda baca; ≥90% huruf terbaca.'),
(9, 5, 'C1',
 'Membaca teks pendek dengan ketepatan kata yang tinggi.',
 'Guru menulis teks 3 kalimat. Katakan: "Baca teks ini dengan suara jelas dari awal sampai akhir." Guru mencatat kesalahan kata.',
 'Rani membawa bekal. Ia makan roti saat istirahat. Setelah itu, Rani minum air.',
 'Paling banyak 2 kesalahan kata dari seluruh teks. Pengulangan untuk koreksi diri tidak dihitung sebagai kesalahan.'),
(9, 6, 'F1',
 'Mengenali sifat bangun datar sederhana: persegi, persegi panjang, segitiga, dan lingkaran.',
 'Guru berkata: "Tunjuk bangun yang saya sebutkan, lalu sebutkan satu sifatnya. Lalu jawab satu pertanyaan tambahan."',
 'Guru menggambar: persegi, persegi panjang, segitiga, lingkaran. Pertanyaan: (1) mana yang sisinya sama panjang semua? (2) mana yang memiliki 3 sisi? (3) mana yang tidak memiliki sudut? (4) mana yang memiliki 4 sudut? (5) bangun apa yang tidak punya sudut sama sekali?',
 '4 dari 5 respons benar.'),
(9, 7, 'A2',
 'Membaca lancar kalimat 5–8 kata dengan tanda titik dan koma sederhana.',
 'Guru berkata: "Baca kalimat ini dengan suara jelas. Berhenti sebentar saat ada koma dan berhenti penuh saat ada titik."',
 'Rani membaca buku di kelas. Budi membawa pensil, buku, dan penghapus. Ibu memasak nasi di dapur.',
 'Minimal 2 dari 3 kalimat dibaca lancar; maksimal 3 kesalahan kata total; jeda titik benar pada minimal 2 kalimat.'),
(9, 8, 'B2',
 'Memilih kata yang lebih tepat untuk menggantikan kata dalam kalimat.',
 'Guru membacakan empat kalimat dengan dua pilihan kata. Anak memilih kata yang lebih tepat sesuai konteks.',
 '"Rina ... jalan di zebra cross." pilihan menyeberangi/melewati. "Budi ... botol minum ke kelas." pilihan membawa/memegang. "Siti ... pengalaman liburannya kepada teman." pilihan bercerita/berkata. "Ali merasa ... karena mendapat hadiah." pilihan gembira/ramai.',
 '3 dari 4 tepat. Kunci: menyeberangi; membawa; bercerita; gembira.'),
(9, 9, 'E2',
 'Menghitung penjumlahan dan pengurangan bilangan 3 digit dengan menyimpan dan meminjam.',
 'Guru berkata: "Kerjakan soal ini dengan cara bersusun."',
 '248 + 137; 365 + 289; 704 − 268; 531 − 176; 620 − 394',
 '4 dari 5 benar.'),
(9, 10, 'D2',
 'Menulis dua kalimat berhubungan tentang pengalaman atau kejadian baru dialami.',
 'Guru berkata secara lisan: "Tulis dua kalimat tentang kegiatan yang baru kamu lakukan hari ini." Tidak ada batas atas panjang.',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 'Minimal 2 kalimat; dua kalimat saling berhubungan; masing-masing memiliki gagasan lengkap; ≤4 kesalahan ejaan dalam 15–30 kata.'),
(9, 11, 'C2',
 'Menemukan satu informasi tersurat dari teks pendek yang dibaca sendiri.',
 'Setelah anak membaca teks C1 L9, tanyakan: "Apa yang dimakan Rani saat istirahat?"',
 'Teks sama dengan C1 L9.',
 'Jawaban tepat: roti.'),
(9, 12, 'F2',
 'Menghitung keliling persegi dan persegi panjang dengan panjang sisi diketahui.',
 'Guru berkata: "Hitung keliling setiap bangun. Jumlahkan semua sisinya."',
 'Persegi sisi 4 cm; persegi sisi 6 cm; persegi panjang 5 × 3 cm; persegi panjang 8 × 2 cm.',
 '3 dari 4 benar.'),
(9, 13, 'EN',
 'Merespons ungkapan kelas dan instruksi sederhana dalam Bahasa Inggris.',
 'Guru berkata: "Listen and do the action." Guru memberi 5 instruksi satu per satu.',
 'Instruksi lisan: Open your book. Close your book. Stand up. Sit down. Raise your hand.',
 'Anak merespons benar 4 dari 5 instruksi.'),
(9, 14, 'KR',
 'Tanggung jawab merawat barang milik sendiri dan milik kelas.',
 'Guru membacakan skenario lalu bertanya: "Apa yang akan kamu lakukan? Mengapa?"',
 '"Kamu meminjam pensil kelas. Setelah dipakai, pensil itu tertinggal di mejamu."',
 'Respons memenuhi 2 dari 3: mengembalikan atau menjaga barang, mengakui pemakaian, memberi alasan tanggung jawab.'),

-- ── L10 ─────────────────────────────────────────────────────────────────────
(10, 1, 'A1',
 'Membaca akurat kata berakhiran -an dan -kan.',
 'Guru berkata: "Baca kata-kata ini satu per satu dengan suara jelas."',
 'makanan, minuman, tulisan, bacaan, mainan, tuliskan, bacakan, bukakan, dengarkan, rapikan',
 'Minimal 8 dari 10 kata dibaca benar tanpa mengeja huruf per huruf.'),
(10, 2, 'B1',
 'Mengenali hubungan makna antara dua kata dalam konteks.',
 'Guru membacakan empat pasangan kalimat. Anak menyebut hubungan kata sasaran: mirip makna atau berlawanan makna.',
 '"Raka rajin belajar. Bima malas belajar." rajin–malas. "Tas itu besar. Kantongnya luas." besar–luas. "Air ini panas. Air itu dingin." panas–dingin. "Dina gembira. Ia sangat senang." gembira–senang.',
 '3 dari 4 tepat. Kunci: berlawanan; mirip; berlawanan; mirip.'),
(10, 3, 'E1',
 'Mengenali perkalian sebagai penjumlahan berulang dan menentukan hasil perkalian kecil.',
 'Guru berkata: "Sebutkan bentuk penjumlahan berulangnya, lalu sebutkan hasilnya."',
 '3 × 2, 4 × 3, 5 × 2, 2 × 6, 3 × 4',
 '4 dari 5 benar.'),
(10, 4, 'D1',
 'Menyalin satu paragraf pendek dari model visual berjarak dengan ejaan sesuai model.',
 'Guru menulis paragraf 4 kalimat, 40–50 kata, di papan berjarak ±2–3 meter. Guru berkata: "Salin paragraf di papan ini sampai selesai."',
 'Paragraf pendek di papan; model tetap terlihat.',
 'Semua kalimat tersalin urut; ≤4 kesalahan salin/ejaan; ≤3 kesalahan kapital atau tanda baca; spasi antarkata benar pada ≥80% pasangan kata.'),
(10, 5, 'C1',
 'Membaca teks pendek dengan lafal dan jeda kalimat yang wajar.',
 'Guru menulis teks 3 kalimat. Katakan: "Baca teks ini. Berhenti sebentar setiap tanda titik." Guru mencatat kesalahan kata dan jeda akhir kalimat.',
 'Bima merapikan tas. Ia memasukkan buku dan pensil. Tas Bima siap dibawa.',
 'Paling banyak 2 kesalahan kata dan anak memberi jeda wajar pada sedikitnya 2 dari 3 akhir kalimat.'),
(10, 6, 'F1',
 'Membaca jam pada jam tepat dan setengah jam serta mengenal satuan hari, minggu, dan bulan.',
 'Guru berkata: "Bacalah waktu pada gambar jam ini, lalu jawab hubungan satuan waktu."',
 'Gambar jam (ditulis angka posisi jarum): 03.00, 07.30, 10.00. Pertanyaan: 1 minggu = berapa hari; 1 bulan kira-kira berapa minggu.',
 '4 dari 5 benar.'),
(10, 7, 'A2',
 'Membaca lancar dua kalimat berurutan dengan jeda koma dan titik tepat.',
 'Guru berkata: "Baca dua kalimat ini berurutan. Perhatikan koma dan titik."',
 'Pagi ini, Sinta datang lebih awal. Ia menyapu kelas, lalu merapikan meja guru.',
 'Maksimal 3 kesalahan kata; jeda koma dan titik benar minimal 3 dari 4 tanda baca; tidak mengeja kata.'),
(10, 8, 'B2',
 'Menyusun ulang kata-kata yang diacak menjadi kalimat bermakna.',
 'Guru membacakan empat kelompok kata acak. Anak menyebut kalimat yang bermakna.',
 '"mencuci – Rani – tangan"; "buku – membaca – Bima"; "di meja – tas – ada"; "karena haus – Ali – minum".',
 '3 dari 4 kalimat bermakna tepat. Contoh kunci: Rani mencuci tangan; Bima membaca buku; tas ada di meja; Ali minum karena haus.'),
(10, 9, 'E2',
 'Menghitung pembagian dasar dengan pembagi 1–5 dan menyelesaikan soal pembagian sederhana.',
 'Guru berkata: "Kerjakan pembagian ini. Untuk soal kalimat, tulis jawabannya saja."',
 '12 : 3; 20 : 5; 16 : 4; 10 : 2; 15 kue dibagi rata kepada 3 anak, berapa tiap anak?',
 '4 dari 5 benar.'),
(10, 10, 'D2',
 'Menulis tiga kalimat berurutan yang menceritakan satu kejadian dari awal hingga akhir.',
 'Guru berkata: "Tulis tiga kalimat tentang satu kejadian. Kalimat pertama bagian awal, kedua bagian tengah, ketiga bagian akhir."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 'Minimal 3 kalimat; urutan awal–tengah–akhir tampak; tidak berpindah topik; ≤5 kesalahan ejaan dalam 25–40 kata.'),
(10, 11, 'C2',
 'Menemukan dua informasi tersurat dari teks pendek yang dibaca sendiri.',
 'Setelah anak membaca teks C1 L10, tanyakan: "Apa yang dirapikan Bima?" dan "Apa saja yang dimasukkan Bima?"',
 'Teks sama dengan C1 L10.',
 '2 dari 2 tepat. Kunci: tas; buku dan pensil.'),
(10, 12, 'F2',
 'Mengonversi satuan panjang cm dan m serta menyelesaikan soal pengukuran panjang sederhana.',
 'Guru berkata: "Ubah satuannya, lalu kerjakan soal panjang ini."',
 '1 m = … cm; 2 m = … cm; 300 cm = … m; pita 2 m dipotong 50 cm, sisa berapa cm?; tali 150 cm ditambah 50 cm, jumlah berapa m?',
 '4 dari 5 benar.'),
(10, 13, 'EN',
 'Menyebutkan kosakata tematik dan merespons pertanyaan singkat tentang benda, warna, angka, atau hari.',
 'Guru berkata: "Look at the words. Answer my questions in English."',
 'Guru menulis di papan: book, pencil, bag, red, blue, Monday, Tuesday, one, two, three. Pertanyaan guru: "What is this?", "What color is it?", "What day is it?", "How many?"',
 'Anak menjawab benar 4 dari 5 pertanyaan.'),
(10, 14, 'KR',
 'Kejujuran saat menghadapi keadaan sulit.',
 'Guru berkata: "Apa yang sebaiknya kamu katakan dan lakukan?"',
 '"Kamu tidak sengaja merobek buku teman, tetapi tidak ada yang melihat."',
 'Respons memenuhi 2 dari 3: mengaku, meminta maaf atau bertanggung jawab, menjelaskan alasan jujur.'),

-- ── L11 ─────────────────────────────────────────────────────────────────────
(11, 1, 'A1',
 'Membaca akurat kata berimbuhan gabungan awalan dan akhiran.',
 'Guru berkata: "Baca kata-kata ini satu per satu. Jangan dieja, langsung baca sebagai kata utuh."',
 'membuatkan, menuliskan, membacakan, memasukkan, menunjukkan, dibacakan, dituliskan, diberikan, dikumpulkan, disampaikan',
 'Minimal 8 dari 10 kata dibaca benar; maksimal 2 kata perlu diulang.'),
(11, 2, 'B1',
 'Mengenali fungsi kata hubung koordinatif dan subordinatif dalam kalimat majemuk.',
 'Guru menulis atau membacakan empat kalimat. Anak menyebut fungsi kata hubung sasaran.',
 '"Rani membaca dan Bima menulis." dan. "Raka ingin bermain, tetapi tugasnya belum selesai." tetapi. "Siti membawa payung karena hujan." karena. "Jika selesai belajar, Ali boleh istirahat." jika.',
 '3 dari 4 tepat. Kunci: penambahan/gabungan; pertentangan; sebab; syarat.'),
(11, 3, 'E1',
 'Menentukan nilai tempat ribuan serta membandingkan dan mengurutkan bilangan 4 digit.',
 'Guru berkata: "Sebutkan nilai angka yang digarisbawahi, lalu urutkan bilangan dari yang terkecil."',
 'Nilai tempat: angka 3 pada 3.482; angka 7 pada 5.761; angka 0 pada 8.095. Urutan: 2.314, 2.413, 2.134, 2.431',
 '3 dari 4 tugas benar.'),
(11, 4, 'D1',
 'Menulis kalimat dengan tanda baca yang benar berdasarkan model tanda baca yang tersedia.',
 'Guru menulis 5 kalimat tanpa kapital awal dan tanpa tanda baca akhir, lalu menulis contoh kecil satu kalimat yang sudah diperbaiki. Guru berkata: "Tulis ulang kalimat ini dengan huruf kapital dan tanda baca yang tepat."',
 'Kalimat tanpa kapital dan tanda baca: 1. ani membawa buku ke sekolah 2. siapa yang menaruh pensil di meja 3. ibu membeli beras telur dan gula 4. kami bermain di halaman saat istirahat 5. wah indah sekali gambar itu',
 'Minimal 4 dari 5 kalimat benar kapital awal dan tanda akhir; ≤3 kesalahan tanda baca total; ≤4 kesalahan ejaan dari seluruh tulisan.'),
(11, 5, 'C1',
 'Membaca teks informasi pendek sambil mengenali bagian-bagian teksnya.',
 'Guru menulis teks 4 kalimat dengan judul. Katakan: "Baca teks ini. Setelah membaca, tunjuk judul, kalimat pembuka, dan satu kalimat rincian."',
 'Manfaat Air — Air dibutuhkan tubuh setiap hari. Kita minum air agar tubuh tidak lemas. Air juga membantu tubuh tetap segar. Karena itu, kita perlu minum cukup air.',
 'Paling banyak 3 kesalahan kata, serta anak dapat menunjuk 2 dari 3 bagian: judul, kalimat pembuka, kalimat rincian.'),
(11, 6, 'F1',
 'Mengenal satuan berat gram dan kilogram serta satuan waktu menit, jam, dan hari.',
 'Guru berkata: "Sebutkan satuan yang tepat dan hubungan antarsatuan berikut."',
 '1 kg = … gram; 1 jam = … menit; 1 hari = … jam; berat sebuah apel lebih tepat gram atau kg; berat beras sekarung lebih tepat gram atau kg.',
 '4 dari 5 benar.'),
(11, 7, 'A2',
 'Membaca lancar tiga kalimat dengan variasi panjang tanpa mengeja kata.',
 'Guru berkata: "Baca teks pendek ini sampai selesai tanpa mengeja huruf per huruf."',
 'Ayah menanam pohon di halaman. Setiap pagi, Dina menyiram tanaman itu. Setelah beberapa minggu, daun baru mulai tumbuh.',
 'Maksimal 4 kesalahan kata; semua kalimat selesai dibaca; tidak ada kata yang dieja huruf per huruf.'),
(11, 8, 'B2',
 'Mengubah kalimat aktif menjadi kalimat pasif dengan mempertahankan makna.',
 'Guru menulis empat kalimat aktif. Anak mengubah menjadi kalimat pasif secara lisan atau tertulis.',
 '"Rani membaca buku." "Budi membuka pintu." "Siti membawa tas." "Ali menulis jawaban."',
 '3 dari 4 tepat. Kunci: Buku dibaca Rani; pintu dibuka Budi; tas dibawa Siti; jawaban ditulis Ali. Variasi pasif yang maknanya sama diterima.'),
(11, 9, 'E2',
 'Menghitung perkalian 2 digit × 1 digit dan pembagian 2 digit : 1 digit.',
 'Guru berkata: "Kerjakan soal ini secara tertulis."',
 '24 × 3; 36 × 2; 47 × 4; 84 : 4; 96 : 3; 75 : 5',
 '5 dari 6 benar.'),
(11, 10, 'D2',
 'Menulis satu paragraf sederhana tentang satu topik dengan gagasan pokok dan minimal dua rincian.',
 'Guru berkata: "Tulis satu paragraf tentang benda, orang, atau kegiatan yang kamu kenal. Tuliskan satu gagasan utama dan sedikitnya dua rincian."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 '1 paragraf 4–5 kalimat; ada gagasan pokok; ada minimal 2 kalimat rincian; ≤6 kesalahan ejaan per 60 kata; tanda akhir benar pada minimal 4 kalimat.'),
(11, 11, 'C2',
 'Menentukan gagasan pokok teks informasi pendek yang dibaca sendiri.',
 'Setelah anak membaca teks C1 L11, tanyakan: "Apa gagasan utama teks ini?"',
 'Teks sama dengan C1 L11.',
 'Jawaban menyebut gagasan utama: air dibutuhkan tubuh / kita perlu cukup minum air.'),
(11, 12, 'F2',
 'Menghitung keliling segitiga dan segi empat tidak beraturan serta mengonversi gram dan kilogram.',
 'Guru berkata: "Hitung keliling bangun ini, lalu ubah satuan berat berikut."',
 'Segitiga sisi 5, 6, 7 cm; segi empat sisi 4, 5, 6, 7 cm; 2 kg = … gram; 3.000 gram = … kg; 1 kg 500 gram = … gram.',
 '4 dari 5 benar.'),
(11, 13, 'EN',
 'Menjawab kalimat tanya sederhana dengan pola What is this?, How many…?, dan What color…?',
 'Guru menunjuk kata atau gambar di papan dan berkata: "Answer in English."',
 'Guru menggambar/menulis: 1 book, 3 pencils, red bag, 2 rulers, blue pen.',
 'Anak memberi jawaban berpola benar 4 dari 5, misalnya "It is a book", "Three pencils."'),
(11, 14, 'KR',
 'Kerja sama dalam tugas bersama teman.',
 'Guru berkata: "Apa yang kamu lakukan agar tugas kelompok selesai?"',
 '"Kelompokmu harus membuat poster. Ada teman yang ingin menggambar, ada yang ingin menulis."',
 'Respons memenuhi 2 dari 3: membagi tugas, mendengarkan teman, menyelesaikan tujuan bersama.'),

-- ── L12 ─────────────────────────────────────────────────────────────────────
(12, 1, 'A1',
 'Membaca akurat kata majemuk dan kata ulang.',
 'Guru berkata: "Baca kata atau frasa ini satu per satu."',
 'kacamata, sapu tangan, rumah sakit, meja makan, matahari, berlari-lari, makan-makan, kupu-kupu, hati-hati, anak-anak',
 'Minimal 8 dari 10 kata atau frasa dibaca benar.'),
(12, 2, 'B1',
 'Menentukan gagasan pokok paragraf sederhana.',
 'Guru menulis satu paragraf empat kalimat bernomor, lalu bertanya: "Kalimat mana yang menjadi gagasan pokok?"',
 '1 "Membaca setiap hari banyak manfaatnya." 2 "Anak dapat mengenal kata baru." 3 "Anak juga lebih mudah memahami cerita." 4 "Karena itu, membaca baik dilakukan secara rutin."',
 'Anak memilih kalimat 1 sebagai gagasan pokok.'),
(12, 3, 'E1',
 'Mengenali pecahan sederhana sebagai bagian dari keseluruhan.',
 'Guru berkata: "Tunjuk pecahan yang menunjukkan setengah, sepertiga, dan seperempat. Lalu sebutkan artinya masing-masing."',
 '1/2, 1/3, 1/4, 2/4, 3/4',
 '4 dari 5 respons benar.'),
(12, 4, 'D1',
 'Menulis paragraf narasi pendek dengan mengikuti kerangka urutan kejadian.',
 'Guru menulis kerangka 3 poin: awal kejadian, kejadian berikutnya, akhir kejadian. Guru berkata: "Tulis satu paragraf narasi dengan mengikuti urutan ini."',
 'Kerangka 3 poin di papan/kertas; model tetap terlihat.',
 '1 paragraf 5–6 kalimat; memuat awal, tengah, akhir; urutan tidak meloncat; ≤4 kesalahan ejaan per 60 kata; ≤3 kesalahan tanda baca/kapital.'),
(12, 5, 'C1',
 'Membaca teks narasi sambil menelusuri urutan kejadiannya.',
 'Guru menulis teks 4 kalimat. Katakan: "Baca teks ini. Setelah membaca, tunjuk kejadian awal, tengah, dan akhir."',
 'Pagi itu, Siti lupa membawa pensil. Ia meminjam pensil kepada Dina. Setelah selesai menulis, Siti mengembalikan pensil itu. Dina senang karena barangnya dijaga.',
 'Paling banyak 3 kesalahan kata, serta anak menunjuk 3 dari 3 unsur urutan dengan benar: kejadian awal, kejadian tengah, dan kejadian akhir.'),
(12, 6, 'F1',
 'Mengenali luas sebagai banyaknya satuan persegi yang mengisi bangun.',
 'Guru berkata: "Hitung banyak kotak satuan pada bangun ini. Bangun dengan kotak lebih banyak berarti luasnya lebih besar."',
 'Guru menggambar petak kotak: A = 3 × 2; B = 4 × 2; C = 3 × 3; D = 5 × 1.',
 '3 dari 4 bangun dihitung atau dibandingkan benar.'),
(12, 7, 'A2',
 'Membaca lancar teks tiga kalimat yang memuat tanda tanya atau tanda seru dengan intonasi berbeda.',
 'Guru berkata: "Baca teks ini dengan suara jelas. Bedakan cara membaca kalimat biasa, tanya, dan seru."',
 'Hari ini kelas kami bersih. Siapa yang merapikan meja guru? Wah, semua teman bekerja sama!',
 'Maksimal 4 kesalahan kata; intonasi tanya dan seru sesuai pada 2 dari 2 kalimat bertanda; jeda akhir kalimat benar.'),
(12, 8, 'B2',
 'Menyusun urutan kalimat yang diacak menjadi paragraf yang kohesif.',
 'Guru menulis empat kalimat bernomor. Anak menyebut urutan yang paling runtut.',
 '1 "Setelah selesai, ia mengembalikan buku ke rak." 2 "Rani ingin membaca cerita." 3 "Ia mengambil buku dari perpustakaan kelas." 4 "Lalu ia membaca di mejanya."',
 'Urutan tepat 2–3–4–1. Lulus bila semua urutan benar.'),
(12, 9, 'E2',
 'Membandingkan, mengurutkan, dan menjumlahkan pecahan berpenyebut sama.',
 'Guru berkata: "Bandingkan (isi >, <, atau =), urutkan, lalu jumlahkan pecahan berikut."',
 '2/5 __ 4/5; 3/8 __ 1/8; urutkan 3/6, 1/6, 5/6; 2/7 + 3/7; 4/9 + 2/9',
 '4 dari 5 benar.'),
(12, 10, 'D2',
 'Menulis narasi pendek berurutan tentang pengalaman sendiri yang mempunyai awal, tengah, akhir.',
 'Guru berkata: "Tulis cerita pendek tentang pengalamanmu. Ceritakan bagian awal, tengah, dan akhir." Tidak diberi kerangka tertulis.',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 'Minimal 6 kalimat; memuat awal, tengah, akhir; urutan waktu dapat diikuti; ≤7 kesalahan ejaan per 80 kata; ≤4 kesalahan kapital/tanda baca.'),
(12, 11, 'C2',
 'Menentukan urutan kejadian dari teks narasi yang dibaca sendiri.',
 'Setelah anak membaca teks C1 L12, tanyakan: "Apa kejadian pertama, kejadian berikutnya, dan kejadian terakhir?"',
 'Teks sama dengan C1 L12.',
 'Anak menyebut 3 dari 3 kejadian utama dalam urutan benar: Siti lupa membawa pensil; meminjam pensil kepada Dina; mengembalikan pensil.'),
(12, 12, 'F2',
 'Menghitung luas persegi dan persegi panjang dengan rumus serta menyelesaikan soal luas sederhana.',
 'Guru berkata: "Hitung luas bangun ini dengan rumus sisi × sisi atau panjang × lebar."',
 'Persegi sisi 5 cm; persegi sisi 7 cm; persegi panjang 8 × 3 cm; persegi panjang 10 × 4 cm; meja pada gambar 6 × 5 cm.',
 '4 dari 5 benar.'),
(12, 13, 'EN',
 'Memperkenalkan diri dan orang lain dengan kalimat sederhana.',
 'Guru berkata: "Introduce yourself and introduce your friend."',
 'Pola di papan: My name is __. I am __ years old. This is my friend. His/Her name is __.',
 'Anak mengucapkan benar 3 dari 4 informasi: nama diri, usia, nama teman, kalimat perkenalan teman.'),
(12, 14, 'KR',
 'Disiplin mengikuti aturan kelas dan jadwal belajar.',
 'Guru berkata: "Apa pilihanmu dan mengapa?"',
 '"Saat jadwal belajar dimulai, kamu masih ingin bermain."',
 'Respons memenuhi 2 dari 3: berhenti bermain, mengikuti jadwal, menyebut alasan disiplin.'),

-- ── L13 ─────────────────────────────────────────────────────────────────────
(13, 1, 'A1',
 'Membaca akurat kata dengan gugus konsonan awal dan tengah.',
 'Guru berkata: "Baca kata-kata ini satu per satu dengan jelas."',
 'strategi, struktur, stasiun, tradisi, translasi, instruksi, ekspresi, produksi, praktik, transportasi',
 'Minimal 8 dari 10 kata dibaca benar; kesalahan pada gugus konsonan maksimal 2.'),
(13, 2, 'B1',
 'Mengenali cara pengembangan paragraf berupa definisi, contoh, atau perbandingan.',
 'Guru membacakan empat potongan paragraf pendek. Anak menyebut jenis pengembangannya: definisi, contoh, atau perbandingan.',
 'A "Disiplin adalah sikap menaati aturan dan waktu." B "Contohnya, anak datang tepat waktu dan membawa alat belajar." C "Belajar sendiri membuat kita fokus, sedangkan belajar kelompok membantu berdiskusi." D "Amanah berarti menjaga kepercayaan yang diberikan orang lain."',
 '3 dari 4 tepat. Kunci: definisi; contoh; perbandingan; definisi.'),
(13, 3, 'E1',
 'Menentukan nilai tempat bilangan cacah sampai 10.000 serta mengenali FPB dan KPK sederhana.',
 'Guru berkata: "Sebutkan nilai angka yang digarisbawahi. Lalu tentukan FPB atau KPK dari pasangan bilangan ini."',
 'Nilai tempat: angka 8 pada 8.426; angka 5 pada 9.503. FPB dari 12 dan 18. KPK dari 4 dan 6. KPK dari 5 dan 10.',
 '4 dari 5 benar.'),
(13, 4, 'D1',
 'Menulis kalimat majemuk dengan kata hubung yang benar berdasarkan pilihan kata hubung yang disediakan.',
 'Guru menulis 6 pasangan kalimat dan daftar kata hubung. Guru berkata: "Gabungkan tiap pasangan kalimat dengan kata hubung yang tepat."',
 'Kata hubung untuk anak: dan, tetapi, karena, sehingga, lalu. Pasangan kalimat: 1. Ibu memasak nasi. Ayah mencuci piring. 2. Rani ingin bermain. Hujan turun deras. 3. Budi membawa payung. Langit terlihat mendung. 4. Dito belajar dengan rajin. Ia mendapat nilai baik. 5. Siti menyapu lantai. Ia merapikan meja. 6. Kakak membeli buku. Adik membeli pensil.',
 'Minimal 5 dari 6 kalimat majemuk tersusun benar dengan kata hubung yang sesuai; ≤4 kesalahan ejaan; tanda baca akhir benar pada minimal 5 kalimat.'),
(13, 5, 'C1',
 'Membaca teks yang memuat kosakata akademik dan menentukan artinya dari konteks.',
 'Guru menulis teks 4 kalimat dan memberi garis bawah pada satu kata. Katakan: "Baca teks ini. Saat sampai kata bergaris bawah, baca juga kalimat di sekitarnya sebelum menjelaskan artinya."',
 'Tanaman membutuhkan air. Akar tanaman menyerap air dari tanah. Air itu membantu batang dan daun tetap segar. Tanaman yang cukup air dapat tumbuh baik. (kata bergaris bawah: menyerap)',
 'Paling banyak 3 kesalahan kata, dan anak membaca kalimat sekitar kata sasaran sebelum memberi arti yang sesuai. Arti diterima: mengambil/masuknya air ke akar.'),
(13, 6, 'F1',
 'Mengenal bangun ruang kubus, balok, dan prisma berdasarkan sisi, rusuk, dan titik sudut.',
 'Guru berkata: "Tunjuk nama bangun ruangnya, lalu sebutkan jumlah sisi, rusuk, atau titik sudut yang saya tanyakan."',
 'Sketsa kubus, balok, prisma segitiga. Pertanyaan: (1) kubus punya berapa sisi; (2) balok punya berapa rusuk; (3) prisma segitiga punya berapa sisi; (4) kubus punya berapa titik sudut; (5) sisi-sisi balok berbentuk bangun datar apa.',
 '4 dari 5 benar.'),
(13, 7, 'A2',
 'Membaca lancar teks 3–4 kalimat dengan intonasi tanda tanya dan seru berbeda dari pernyataan.',
 'Guru berkata: "Baca teks ini dengan intonasi yang sesuai tanda baca."',
 'Siswa membaca instruksi di papan. Mengapa kita harus mengikuti aturan? Aturan membuat kegiatan belajar lebih tertib. Ayo, kita mulai sekarang!',
 'Maksimal 5 kesalahan kata; intonasi tanya dan seru sesuai pada 2 dari 2; tidak mengeja kata panjang.'),
(13, 8, 'B2',
 'Menambahkan kalimat penjelas yang sesuai untuk mengembangkan gagasan pokok.',
 'Guru menulis satu gagasan pokok dan tiga pilihan kalimat penjelas. Anak memilih dua yang sesuai.',
 'Gagasan pokok: "Menjaga kebersihan kelas adalah tanggung jawab bersama." Pilihan: A "Anak dapat membuang sampah pada tempatnya." B "Meja yang bersih membuat belajar nyaman." C "Sepeda baru berwarna merah."',
 'Lulus bila anak memilih A dan B, bukan C.'),
(13, 9, 'E2',
 'Menghitung perkalian 2 digit × 2 digit dan pembagian 3 digit : 1 digit dengan sisa.',
 'Guru berkata: "Kerjakan soal ini secara tertulis. Jika ada sisa, tulis sisanya."',
 '23 × 14; 36 × 25; 48 × 17; 125 : 4; 236 : 5; 319 : 6',
 '5 dari 6 benar.'),
(13, 10, 'D2',
 'Menulis paragraf deskripsi dengan minimal tiga ciri teramati dari satu benda atau tempat.',
 'Guru berkata: "Pilih satu benda atau tempat yang kamu kenal. Tulis satu paragraf yang menjelaskan sedikitnya tiga cirinya."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 '1 paragraf 6–8 kalimat; memuat minimal 3 ciri yang dapat diamati; tetap pada satu objek/tempat; ≤7 kesalahan ejaan per 90 kata.'),
(13, 11, 'C2',
 'Menentukan makna kata dari konteks paragraf yang dibaca sendiri.',
 'Setelah anak membaca teks C1 L13, tanyakan: "Apa arti kata menyerap dalam teks ini?"',
 'Teks sama dengan C1 L13.',
 'Jawaban diterima: akar mengambil air dari tanah / air masuk ke akar.'),
(13, 12, 'F2',
 'Menghitung volume kubus dan balok dengan rumus serta menyelesaikan soal volume sederhana.',
 'Guru berkata: "Hitung volume dengan mengalikan panjang, lebar, dan tinggi."',
 'Kubus sisi 4 cm; kubus sisi 6 cm; balok 5 × 3 × 2 cm; balok 8 × 4 × 2 cm; kotak 10 × 5 × 3 cm.',
 '4 dari 5 benar.'),
(13, 13, 'EN',
 'Mendeskripsikan benda atau orang dengan kalimat sederhana.',
 'Guru berkata: "Make sentences about this thing or person."',
 'Guru menggambar/menulis di papan: buku besar berwarna biru, pensil pendek, anak berambut panjang. Kata bantu: big, small, blue, short, long hair.',
 'Anak membuat 3 dari 4 kalimat deskripsi yang dapat dipahami dan sesuai objek.'),
(13, 14, 'KR',
 'Empati terhadap perasaan orang lain.',
 'Guru berkata: "Menurutmu bagaimana perasaannya? Apa yang bisa kamu lakukan?"',
 '"Temanmu terlihat sedih karena hasil gambarnya ditertawakan."',
 'Respons memenuhi 2 dari 3: mengenali perasaan teman, tidak mengejek, memberi dukungan atau bantuan.'),

-- ── L14 ─────────────────────────────────────────────────────────────────────
(14, 1, 'A1',
 'Membaca akurat kata serapan panjang yang umum di pelajaran sekolah.',
 'Guru berkata: "Baca kata-kata ini satu per satu tanpa mengeja."',
 'komunikasi, organisasi, teknologi, industri, informasi, administrasi, kreativitas, aktivitas, transportasi, demonstrasi',
 'Minimal 8 dari 10 kata dibaca benar tanpa mengeja huruf per huruf.'),
(14, 2, 'B1',
 'Membedakan pernyataan fakta dari opini dalam teks pendek.',
 'Guru membacakan empat kalimat. Anak menyebut tiap kalimat sebagai fakta atau opini.',
 '"Kelas dimulai pukul delapan." "Belajar pagi lebih menyenangkan." "Perpustakaan memiliki dua rak buku." "Buku cerita itu paling bagus."',
 '3 dari 4 tepat. Kunci: fakta; opini; fakta; opini.'),
(14, 3, 'E1',
 'Mengenali desimal persepuluhan dan perseratusan serta hubungannya dengan pecahan sederhana.',
 'Guru berkata: "Bacalah desimal ini, lalu pasangkan dengan pecahan yang nilainya sama."',
 '0,5 = 5/10; 0,25 = 25/100; 0,75 = 75/100; 0,3 = 3/10; 0,08 = 8/100',
 '4 dari 5 pasangan benar.'),
(14, 4, 'D1',
 'Menulis paragraf informasi pendek berdasarkan bagan atau kerangka poin-poin.',
 'Guru menulis bagan 4 poin tentang topik dikenal. Guru berkata: "Gunakan poin-poin ini untuk menulis satu paragraf informasi."',
 'Bagan/poin tentang hewan, tumbuhan, tempat, atau kegiatan; model tetap terlihat.',
 '1 paragraf 5–7 kalimat; memuat gagasan utama dan minimal 3 poin dari bagan; ≤5 kesalahan ejaan per 75 kata; ≤3 kesalahan kapital/tanda baca.'),
(14, 5, 'C1',
 'Membaca teks yang memuat kalimat majemuk kompleks dengan tepat.',
 'Guru menulis teks 5 kalimat. Katakan: "Baca teks ini dengan memperhatikan koma dan kata hubung." Guru mencatat kesalahan kata dan jeda pada koma/titik.',
 'Ketika hujan turun, anak-anak tetap belajar di kelas. Mereka tidak bermain di halaman karena lantai menjadi licin. Walaupun begitu, suasana kelas tetap menyenangkan. Guru mengajak anak membaca cerita. Setelah hujan reda, mereka pulang dengan tertib.',
 'Paling banyak 4 kesalahan kata, dan anak memberi jeda wajar pada sedikitnya 3 dari 5 tanda baca utama.'),
(14, 6, 'F1',
 'Membaca dan menafsirkan tabel data dan diagram batang sederhana.',
 'Guru berkata: "Bacalah data ini. Jawab mana yang paling banyak, paling sedikit, berapa selisihnya, dan dua pertanyaan lain."',
 'Tabel buku dibaca: Ani 6, Budi 4, Cici 8, Dodi 5. Pertanyaan: (1) siapa paling banyak; (2) siapa paling sedikit; (3) selisih Ani dan Budi; (4) jumlah Budi dan Dodi; (5) berapa orang dalam data.',
 '4 dari 5 benar.'),
(14, 7, 'A2',
 'Membaca lancar teks empat kalimat dengan kata serapan umum.',
 'Guru berkata: "Baca teks ini sampai selesai dengan lancar. Jangan mengeja kata panjang."',
 'Komunikasi yang baik membuat kerja kelompok lebih mudah. Setiap anggota menyampaikan informasi dengan jelas. Teknologi membantu siswa mencari bahan belajar. Namun, penggunaan teknologi harus tetap bijak.',
 'Maksimal 5 kesalahan kata; tidak mengeja kata serapan; minimal 3 dari 4 kalimat dibaca lancar.'),
(14, 8, 'B2',
 'Memilih diksi yang lebih tepat untuk konteks formal dari pilihan yang disediakan.',
 'Guru membacakan empat kalimat konteks formal dengan dua pilihan kata. Anak memilih diksi yang lebih tepat.',
 '"Siswa diminta (ngumpulin/mengumpulkan) tugas." "Guru akan (memberi/ngasih) penjelasan." "Kami (mohon/minta dong) izin bertanya." "Kegiatan akan (dilaksanakan/dikerjain) besok."',
 '3 dari 4 tepat. Kunci: mengumpulkan; memberi; mohon; dilaksanakan.'),
(14, 9, 'E2',
 'Menghitung penjumlahan dan pengurangan desimal serta mengubah pecahan biasa ke desimal sederhana.',
 'Guru berkata: "Kerjakan operasi desimal ini, lalu ubah pecahan menjadi desimal."',
 '2,5 + 1,3; 4,75 + 2,10; 6,8 − 3,4; 9,50 − 2,25; 1/2 = ?; 1/4 = ?',
 '5 dari 6 benar.'),
(14, 10, 'D2',
 'Menulis teks informasi pendek tentang topik dikenal dengan gagasan utama dan dua pendukung.',
 'Guru berkata: "Tulis teks informasi pendek tentang topik yang kamu ketahui. Tuliskan gagasan utama dan dua informasi pendukung."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 '1–2 paragraf, 80–110 kata; ada gagasan utama; ada minimal 2 informasi pendukung; ≤8 kesalahan ejaan per 110 kata; paragraf jelas bila lebih dari satu.'),
(14, 11, 'C2',
 'Membedakan informasi utama dari informasi pendukung dalam teks yang dibaca sendiri.',
 'Setelah anak membaca teks C1 L14, tanyakan: "Informasi utama teks ini apa?" dan "Sebutkan dua informasi pendukungnya."',
 'Teks sama dengan C1 L14.',
 'Lulus bila menyebut informasi utama anak-anak tetap belajar saat hujan dan sedikitnya 1 dari 2 pendukung yang benar: lantai licin, guru mengajak membaca cerita, atau pulang setelah hujan reda.'),
(14, 12, 'F2',
 'Menghitung rata-rata (mean) dari sekumpulan data dan menyelesaikan soal data sederhana.',
 'Guru berkata: "Jumlahkan semua data, lalu bagi dengan banyak data."',
 'Data nilai: 6, 8, 7, 9; data buku: 4, 5, 6, 5; data tinggi tanaman: 10, 12, 14; data penjualan: 3, 7, 5, 5.',
 '3 dari 4 mean benar.'),
(14, 13, 'EN',
 'Menceritakan kegiatan sehari-hari dengan simple present tense sederhana.',
 'Guru berkata: "Tell me your daily activities in English."',
 'Pola di papan: I wake up at __. I go to school. I study. I play. I sleep at __.',
 'Anak mengucapkan 4 dari 5 kalimat kegiatan dengan urutan masuk akal.'),
(14, 14, 'KR',
 'Kemandirian mencoba menyelesaikan masalah sebelum meminta bantuan.',
 'Guru berkata: "Apa langkah pertamamu?"',
 '"Kamu tidak paham satu soal. Guru sedang membantu teman lain."',
 'Respons memenuhi 2 dari 3: mencoba membaca ulang, menggunakan contoh atau catatan, meminta bantuan dengan tepat setelah mencoba.'),

-- ── L15 ─────────────────────────────────────────────────────────────────────
(15, 1, 'A1',
 'Membaca akurat frasa nominal kompleks.',
 'Guru berkata: "Baca frasa ini satu per satu sebagai satu kelompok kata."',
 'program pendidikan nasional; kegiatan ekstrakurikuler sekolah; perpustakaan daerah kota; laporan hasil pengamatan; jadwal pelajaran mingguan; lomba kebersihan kelas; kegiatan olahraga pagi; peraturan lalu lintas sederhana',
 'Minimal 6 dari 8 frasa dibaca lancar dan utuh.'),
(15, 2, 'B1',
 'Menganalisis struktur teks eksposisi atau argumentasi sederhana.',
 'Guru menulis teks pendek tiga kalimat, lalu anak menyebut bagian klaim, argumen, dan simpulan.',
 '"Membaca rutin perlu dibiasakan. Kebiasaan ini menambah kosakata dan membantu anak memahami pelajaran. Jadi, anak sebaiknya menyediakan waktu membaca setiap hari."',
 '3 dari 3 unsur tepat. Kunci: kalimat 1 = klaim; kalimat 2 = argumen; kalimat 3 = simpulan.'),
(15, 3, 'E1',
 'Mengenali bilangan bulat negatif, menentukan letaknya pada garis bilangan, dan mengenal konsep bilangan berlawanan.',
 'Guru berkata: "Sebutkan bilangan yang lebih besar dari tiap pasangan. Lalu urutkan bilangan ini dari yang terkecil. Lalu sebutkan bilangan yang berlawanan dari -4."',
 'Pasangan: -3 dan 2; -5 dan -1; 0 dan -4. Urutan: -2, 4, -6, 1, 0. Bilangan berlawanan: -4.',
 '4 dari 5 tugas benar.'),
(15, 4, 'D1',
 'Menulis teks deskripsi pendek berdasarkan catatan atau bagan terstruktur.',
 'Guru menulis bagan: nama objek, bentuk/warna, bagian penting, fungsi/kesan. Guru berkata: "Tulis teks deskripsi berdasarkan catatan ini."',
 'Bagan deskripsi 4–5 poin; model tetap terlihat.',
 '2 paragraf atau 1 paragraf panjang 80–100 kata; memuat minimal 4 unsur bagan; rincian tersusun jelas; ≤5 kesalahan ejaan per 100 kata; paragraf/spasi jelas.'),
(15, 5, 'C1',
 'Membaca teks argumentasi pendek dengan strategi prediksi isi berdasarkan judul atau kalimat awal.',
 'Guru menulis judul dan kalimat pertama saja lebih dulu. Katakan: "Baca judul dan kalimat pertama, lalu tebak teks ini akan membahas apa." Setelah anak menjawab, guru menulis sisa teks dan anak membaca seluruh teks.',
 'Membaca Setiap Hari — Membaca setiap hari perlu dibiasakan. Kebiasaan ini menambah kosakata. Anak yang sering membaca juga lebih mudah memahami pelajaran. Membaca tidak harus lama, tetapi perlu dilakukan rutin. Karena itu, anak sebaiknya menyediakan waktu membaca setiap hari.',
 'Prediksi anak berhubungan dengan kebiasaan atau manfaat membaca, dan pembacaan teks penuh paling banyak 5 kesalahan kata.'),
(15, 6, 'F1',
 'Mengenal sifat segitiga dan jajargenjang serta jenis segitiga berdasarkan sisi dan sudut.',
 'Guru berkata: "Tunjuk jenis segitiga atau bangun yang saya sebutkan, lalu sebutkan satu sifatnya."',
 'Sketsa: segitiga sama sisi, segitiga sama kaki, segitiga siku-siku, segitiga sembarang, jajargenjang.',
 '4 dari 5 identifikasi atau sifat benar.'),
(15, 7, 'A2',
 'Membaca lancar teks empat kalimat dengan frasa panjang dan tanpa pengulangan kata untuk menebak.',
 'Guru berkata: "Baca teks ini dengan tempo wajar. Jangan mengulang kata berkali-kali untuk menebak."',
 'Program kebersihan sekolah dimulai setiap Jumat pagi. Semua siswa membawa alat kebersihan dari rumah. Kegiatan ekstrakurikuler sekolah tetap berjalan setelah istirahat. Guru memberi laporan hasil pengamatan kepada kepala sekolah.',
 'Maksimal 5 kesalahan kata; pengulangan untuk menebak maksimal 2 kali total; minimal 3 dari 4 kalimat dibaca lancar.'),
(15, 8, 'B2',
 'Menyusun paragraf argumentasi dengan klaim dan sedikitnya satu argumen pendukung.',
 'Guru memberi topik lisan: "Apakah membaca setiap hari itu penting?" Anak menyusun paragraf lisan atau tertulis singkat.',
 'Topik lisan dari guru; tanpa bahan cetak.',
 'Lulus bila respons memuat klaim jelas dan sedikitnya satu argumen pendukung. Contoh: Membaca penting karena menambah pengetahuan/kosakata.'),
(15, 9, 'E2',
 'Menghitung penjumlahan dan pengurangan bilangan bulat, termasuk negatif, dalam konteks sederhana.',
 'Guru berkata: "Kerjakan soal bilangan bulat ini. Untuk soal konteks, tulis angka hasilnya."',
 '−3 + 7; 5 + (−8); −6 − 4; −2 − (−5); suhu −1°C naik 6 derajat; ketinggian 3 m turun 7 m',
 '5 dari 6 benar.'),
(15, 10, 'D2',
 'Menulis paragraf argumentasi dengan klaim jelas dan minimal satu alasan pendukung.',
 'Guru berkata: "Tulis pendapatmu tentang satu hal di sekolah atau rumah. Berikan sedikitnya satu alasan."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 '1 paragraf 6–8 kalimat; ada klaim/pendapat jelas; ada minimal 1 alasan relevan; ≤8 kesalahan ejaan per 110 kata; tanda baca akhir benar pada ≥80% kalimat.'),
(15, 11, 'C2',
 'Menyimpulkan pesan atau isi teks berdasarkan bukti yang ada dalam teks.',
 'Setelah anak membaca teks C1 L15, tanyakan: "Apa pesan teks ini? Sebutkan satu bukti dari teks."',
 'Teks sama dengan C1 L15.',
 'Jawaban memuat pesan membaca perlu dibiasakan/rutin dan satu bukti: menambah kosakata atau membantu memahami pelajaran.'),
(15, 12, 'F2',
 'Menghitung luas segitiga dan jajargenjang serta luas gabungan sederhana.',
 'Guru berkata: "Hitung luas bangun ini. Untuk gabungan, hitung tiap bagian lalu jumlahkan."',
 'Segitiga alas 8 cm tinggi 5 cm; segitiga alas 10 cm tinggi 6 cm; jajargenjang alas 9 cm tinggi 4 cm; jajargenjang alas 12 cm tinggi 5 cm; gabungan persegi panjang 6 × 4 cm dan segitiga alas 6 cm tinggi 3 cm.',
 '4 dari 5 benar.'),
(15, 13, 'EN',
 'Mengungkapkan perasaan dan pendapat sederhana.',
 'Guru berkata: "Tell your feeling and your opinion."',
 'Situasi lisan: mendapat nilai baik, hujan saat ingin bermain, teman membantu. Pola di papan: I feel __. I think it is __ because __.',
 'Anak memberi respons sesuai situasi 3 dari 4, minimal memuat perasaan atau pendapat sederhana.'),
(15, 14, 'KR',
 'Integritas melakukan yang benar walau tidak ada yang melihat.',
 'Guru berkata: "Apa yang kamu lakukan?"',
 '"Kamu menemukan uang di lantai kelas saat kelas sepi."',
 'Respons memenuhi 2 dari 3: tidak mengambil untuk diri sendiri, melapor atau menyerahkan, memberi alasan benar walau tidak diawasi.'),

-- ── L16 ─────────────────────────────────────────────────────────────────────
(16, 1, 'A1',
 'Membaca akurat kata berimbuhan konfiks.',
 'Guru berkata: "Baca kata-kata ini satu per satu dengan jelas dan utuh."',
 'pemberitahuan, ketidakhadiran, pembelajaran, penyelenggaraan, pertandingan, perkembangan, penggunaan, pengamatan, perbaikan, keberhasilan',
 'Minimal 8 dari 10 kata dibaca benar; maksimal 2 kata terputus-putus.'),
(16, 2, 'B1',
 'Menentukan arti kosakata akademik dari konteks teks ilmiah populer.',
 'Guru membacakan empat kalimat. Anak menjelaskan arti kata sasaran berdasarkan konteks.',
 '"Air menguap saat terkena panas, yaitu berubah menjadi uap." Apa arti menguap? "Tanaman menyerap air melalui akar." Apa arti menyerap? "Hewan beradaptasi agar dapat hidup di lingkungannya." Apa arti beradaptasi? "Data dikumpulkan untuk mengetahui hasil pengamatan." Apa arti data?',
 '3 dari 4 tepat. Kunci/padanan: berubah jadi uap; mengambil/masuk ke dalam; menyesuaikan diri; informasi hasil catatan/pengamatan.'),
(16, 3, 'E1',
 'Mengenali rasio dan menyederhanakan perbandingan dua besaran.',
 'Guru berkata: "Bacalah perbandingan ini, lalu sederhanakan jika bisa."',
 '6:9, 8:12, 10:15, 12:16, 5:20',
 '4 dari 5 disederhanakan benar.'),
(16, 4, 'D1',
 'Menulis kalimat yang benar secara tata bahasa dan ejaan berdasarkan model kalimat.',
 'Guru menulis pola S–P–O–K dengan satu contoh, lalu 8 kelompok kata acak. Guru berkata: "Susun kelompok kata ini menjadi kalimat yang benar seperti pola."',
 'Pola dicontohkan guru: S–P–O–K. Contoh: Anak-anak membaca buku di perpustakaan. Kelompok kata: 1. menanam/pohon mangga/di halaman/Ayah 2. membaca/di kamar/buku cerita/Dina 3. membeli/di pasar/sayur segar/Ibu 4. membersihkan/halaman sekolah/pagi tadi/para siswa 5. menulis/di buku tugas/cerita pendek/Rafi 6. menyiram/setiap sore/tanaman bunga/Nenek 7. memperbaiki/di ruang tamu/kursi kayu/Paman 8. mengumpulkan/setelah istirahat/tugas kelompok/murid-murid.',
 'Minimal 7 dari 8 kalimat tersusun gramatikal; kapital dan tanda akhir benar pada minimal 7 kalimat; ≤5 kesalahan ejaan total.'),
(16, 5, 'C1',
 'Membaca teks ilmiah populer dengan strategi menemukan informasi kunci secara cepat.',
 'Guru menulis teks 5 kalimat. Katakan: "Baca cepat dalam hati untuk mencari apa yang berubah saat air dipanaskan. Setelah itu baca nyaring kalimat yang memuat jawabannya."',
 'Air dapat berubah bentuk karena panas. Saat dipanaskan, sebagian air berubah menjadi uap. Proses ini disebut menguap. Uap air dapat terlihat seperti asap tipis. Perubahan ini sering terjadi saat air mendidih.',
 'Anak menunjuk atau membaca kalimat kunci tentang air berubah menjadi uap, lalu membaca nyaring kalimat itu dengan paling banyak 1 kesalahan kata.'),
(16, 6, 'F1',
 'Mengenal lingkaran: jari-jari, diameter, pi, dan hubungan diameter dengan jari-jari.',
 'Guru berkata: "Tunjuk jari-jari dan diameter pada gambar. Lalu jawab hubungan antara jari-jari dan diameter, dan nilai pi."',
 'Sketsa lingkaran berpusat O; garis OA sebagai jari-jari; garis AB melalui pusat sebagai diameter. Pertanyaan: (1) tunjuk jari-jari; (2) tunjuk diameter; (3) diameter = 2 × jari-jari benar/salah; (4) pi kira-kira berapa; (5) jika jari-jari 7, diameter berapa.',
 '4 dari 5 benar.'),
(16, 7, 'A2',
 'Membaca lancar teks 4–5 kalimat dengan frasa dibaca sebagai satu unit makna.',
 'Guru berkata: "Baca teks ini dengan memperhatikan kelompok kata. Jangan berhenti di setiap kata jika tidak perlu."',
 'Pemberitahuan kegiatan sekolah ditempel di papan informasi. Siswa membaca jadwal pertandingan dengan teliti. Ketidakhadiran peserta harus dilaporkan kepada panitia. Pembelajaran di kelas tetap berlangsung seperti biasa. Semua pengumuman disampaikan sebelum istirahat.',
 'Maksimal 6 kesalahan kata; minimal 4 dari 5 kalimat dibaca lancar; jeda frasa tidak berlebihan.'),
(16, 8, 'B2',
 'Menggunakan kosakata akademik yang tepat dalam kalimat berdasarkan konteks.',
 'Guru memberi empat konteks dan pilihan kata. Anak membuat kalimat memakai kata yang tepat.',
 'Kata pilihan: mengamati, menyerap, menguap, data. Konteks: melihat benda dengan teliti; air masuk ke akar; air berubah jadi uap; catatan hasil pengamatan.',
 '3 dari 4 kalimat memakai kata yang tepat sesuai konteks. Ejaan dan tulisan tangan tidak dinilai.'),
(16, 9, 'E2',
 'Menghitung nilai perbandingan dan menyelesaikan soal perbandingan sederhana.',
 'Guru berkata: "Kerjakan soal perbandingan ini secara tertulis."',
 '2:3 = 10:__; 4:5 = __:20; resep 2 gelas sirup untuk 6 gelas air, berapa sirup untuk 12 gelas?; skala 1 cm = 5 km, 4 cm = __ km?; 18 permen dibagi rasio 1:2',
 '4 dari 5 benar.'),
(16, 10, 'D2',
 'Menulis teks prosedur atau deskripsi singkat yang logis urutannya.',
 'Guru berkata: "Pilih salah satu: tulis cara melakukan sesuatu, atau tulis deskripsi satu benda/tempat. Buat urutannya jelas."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 '1–2 paragraf, 90–120 kata; urutan langkah atau rincian logis; tidak ada bagian utama yang membingungkan; ≤8 kesalahan ejaan per 120 kata.'),
(16, 11, 'C2',
 'Membedakan pernyataan fakta dari opini dalam teks yang dibaca sendiri.',
 'Setelah anak membaca teks C1 L16, guru membacakan tiga pernyataan dan anak menyebut fakta atau opini: "Air dapat berubah menjadi uap." "Menguap adalah proses yang paling menarik." "Air mendidih dapat menghasilkan uap."',
 'Teks sama dengan C1 L16.',
 '2 dari 3 tepat. Kunci: fakta; opini; fakta.'),
(16, 12, 'F2',
 'Menghitung keliling lingkaran dan menyelesaikan soal terapan keliling sederhana.',
 'Guru berkata: "Hitung keliling lingkaran. Gunakan 22/7 jika jari-jari atau diameter kelipatan 7, dan 3,14 jika sesuai."',
 'Diameter 14 cm; jari-jari 7 cm; diameter 10 cm; jari-jari 5 cm; roda diameter 28 cm berputar satu kali, jarak tempuh berapa cm?',
 '4 dari 5 benar.'),
(16, 13, 'EN',
 'Melakukan percakapan singkat dua arah tentang topik dikenal.',
 'Guru berkata: "Ask and answer with me." Guru melakukan tanya jawab bergantian.',
 'Topik: school, food, hobby. Contoh pertanyaan: What is your favorite food? Do you like reading? What do you do at school?',
 'Anak dapat bertanya atau menjawab secara sesuai 4 dari 5 giliran percakapan.'),
(16, 14, 'KR',
 'Menghargai perbedaan pendapat atau latar belakang teman.',
 'Guru berkata: "Bagaimana kamu menanggapi temanmu?"',
 '"Dalam diskusi, temanmu punya pendapat berbeda darimu."',
 'Respons memenuhi 2 dari 3: mendengarkan, tidak merendahkan, menyampaikan pendapat sendiri dengan sopan.'),

-- ── L17 ─────────────────────────────────────────────────────────────────────
(17, 1, 'A1',
 'Membaca akurat kata teknis bidang ilmu sederhana.',
 'Guru berkata: "Baca istilah-istilah ini satu per satu."',
 'fotosintesis, ekosistem, demokrasi, gravitasi, evaporasi, populasi, konstitusi, metabolisme, magnetisme, revolusi',
 'Minimal 8 dari 10 kata dibaca benar.'),
(17, 2, 'B1',
 'Menganalisis perangkat kohesi leksikal antar-kalimat.',
 'Guru menulis paragraf pendek, lalu bertanya: "Kata apa yang diulang dalam paragraf ini?" "Kata hewan merujuk pada apa?" "Ungkapan si manis itu merujuk pada apa?" "Semua sebutan itu membicarakan siapa?"',
 '"Kucing adalah hewan peliharaan yang lincah. Hewan ini suka bergerak cepat. Si manis itu juga pandai menjaga keseimbangan. Kucing sering melompat dari tempat tinggi."',
 '3 dari 4 tepat. Kunci: pengulangan kucing; hipernim hewan merujuk pada kucing; si manis merujuk pada kucing; semua sebutan membicarakan kucing.'),
(17, 3, 'E1',
 'Mengenali pola bilangan dan menemukan aturan barisan beraturan.',
 'Guru berkata: "Lanjutkan dua bilangan berikutnya, lalu sebutkan aturannya."',
 '3, 6, 9, 12, …; 40, 35, 30, 25, …; 2, 4, 8, 16, …; 1, 4, 9, 16, …',
 '3 dari 4 barisan benar lengkap dengan aturan.'),
(17, 4, 'D1',
 'Menulis paragraf argumentasi dengan klaim dan argumen berdasarkan kerangka.',
 'Guru menulis kerangka: klaim, alasan 1, alasan 2, penutup. Guru berkata: "Tulis paragraf argumentasi dengan mengikuti kerangka ini."',
 'Kerangka argumentasi 4 bagian; model tetap terlihat.',
 '1 paragraf 7–9 kalimat; memuat klaim jelas, minimal 2 alasan, dan penutup; urutan sesuai kerangka; ≤5 kesalahan ejaan per 100 kata; ≤4 kesalahan tanda baca/kapital.'),
(17, 5, 'C1',
 'Membaca teks dengan mengidentifikasi sudut pandang atau tujuan penulis.',
 'Guru menulis teks 6 kalimat. Katakan: "Baca teks ini. Sambil membaca, perhatikan apakah penulis mendukung atau menolak kebiasaan yang dibahas."',
 'Membawa botol minum sendiri adalah kebiasaan yang baik. Anak tidak perlu sering membeli minuman kemasan. Sampah plastik di kelas juga dapat berkurang. Kebiasaan ini memang perlu diingat setiap pagi. Namun, manfaatnya lebih besar daripada repotnya. Karena itu, siswa sebaiknya membawa botol minum sendiri.',
 'Paling banyak 5 kesalahan kata, dan anak menyebut sudut pandang penulis: mendukung membawa botol minum sendiri, dengan satu bukti dari teks.'),
(17, 6, 'F1',
 'Membaca denah berskala dan menentukan jarak sebenarnya dari skala yang diberikan.',
 'Guru berkata: "Bacalah skala denah ini. Lalu sebutkan jarak sebenarnya untuk tiap garis yang ditunjuk."',
 'Denah sederhana: skala 1 cm = 2 km. Jarak pada denah: Rumah–Sekolah 3 cm; Rumah–Pasar 4 cm; Sekolah–Taman 2 cm; Pasar–Taman 5 cm.',
 '3 dari 4 jarak sebenarnya benar.'),
(17, 7, 'A2',
 'Membaca lancar teks lima kalimat dari konteks sains atau sosial dengan jeda dan intonasi alami.',
 'Guru berkata: "Baca teks ini dengan lancar dan perhatikan tanda baca."',
 'Fotosintesis terjadi pada tumbuhan hijau. Tumbuhan membutuhkan cahaya matahari, air, dan udara. Dalam ekosistem, setiap makhluk hidup memiliki peran. Apa yang terjadi jika satu bagian ekosistem rusak? Kita perlu menjaga lingkungan bersama-sama!',
 'Maksimal 6 kesalahan kata; jeda tanda baca benar minimal 5 dari 6; intonasi tanya dan seru sesuai.'),
(17, 8, 'B2',
 'Merevisi kalimat untuk meningkatkan ketepatan pilihan kata dan kejelasan gagasan.',
 'Guru membacakan tiga kalimat lemah. Anak merevisi secara lisan atau tertulis.',
 '"Belajar itu bagus karena bagus." "Kita harus rajin supaya hal itu baik." "Membaca membuat kita dapat sesuatu."',
 '2 dari 3 revisi lebih jelas dan tepat. Contoh diterima: Belajar penting karena membantu memahami pelajaran; kita harus rajin agar tugas selesai; membaca menambah pengetahuan/kosakata.'),
(17, 9, 'E2',
 'Menghitung operasi campuran bilangan bulat dengan urutan operasi yang benar.',
 'Guru berkata: "Kerjakan operasi campuran ini. Dahulukan kali dan bagi sebelum tambah dan kurang."',
 '6 + 4 × 3; 20 − 12 : 3; (8 + 4) × 2; −5 + 3 × 4; 18 : 3 − 7; 10 − (6 + 2)',
 '5 dari 6 benar.'),
(17, 10, 'D2',
 'Menulis teks eksposisi pendek dengan gagasan pokok dan minimal dua kalimat pendukung.',
 'Guru berkata: "Tulis teks pendek yang menjelaskan satu topik. Tuliskan gagasan pokok dan sedikitnya dua kalimat pendukung."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 '2 paragraf atau 1 paragraf panjang, 100–140 kata; gagasan pokok jelas; minimal 2 dukungan relevan; ≤8 kesalahan ejaan per 130 kata; struktur penjelasan dapat diikuti.'),
(17, 11, 'C2',
 'Menganalisis sudut pandang penulis berdasarkan pilihan kata dan argumen dalam teks.',
 'Setelah anak membaca teks C1 L17, tanyakan: "Penulis mendukung kebiasaan apa?" "Kata atau kalimat mana yang menunjukkan dukungan itu?" "Apa argumen penulis?"',
 'Teks sama dengan C1 L17.',
 '2 dari 3 tepat. Kunci: mendukung membawa botol minum sendiri; bukti: kebiasaan yang baik / manfaatnya lebih besar; argumen: mengurangi sampah / tidak perlu membeli minuman kemasan.'),
(17, 12, 'F2',
 'Menghitung luas trapesium dan belah ketupat serta luas bangun datar gabungan sederhana.',
 'Guru berkata: "Hitung luas dengan rumus yang sesuai. Untuk gabungan, pisahkan menjadi bangun yang kamu kenal."',
 'Trapesium sisi sejajar 8 dan 12 cm, tinggi 5 cm; trapesium 6 dan 10 cm, tinggi 4 cm; belah ketupat diagonal 10 dan 8 cm; belah ketupat diagonal 12 dan 9 cm; gabungan persegi panjang 8 × 4 cm dan segitiga alas 8 cm tinggi 3 cm.',
 '4 dari 5 benar.'),
(17, 13, 'EN',
 'Membaca paragraf pendek Bahasa Inggris dan menjawab pertanyaan isi.',
 'Guru berkata: "Read this text aloud. Then answer the questions."',
 'Teks di papan: Rina has a small cat. The cat is white. It likes fish. Rina plays with the cat every afternoon. Pertanyaan: Who has a cat? What color is the cat? What does it like? When does Rina play with it?',
 'Anak membaca cukup lancar dan menjawab benar 3 dari 4 pertanyaan isi.'),
(17, 14, 'KR',
 'Kepemimpinan sederhana melalui pengendalian diri dan memberi contoh baik.',
 'Guru berkata: "Apa yang bisa kamu lakukan agar teman lain ikut tertib?"',
 '"Saat guru keluar sebentar, beberapa teman mulai ribut."',
 'Respons memenuhi 2 dari 3: tetap tertib, mengajak teman dengan sopan, memberi contoh tanpa memaksa.'),

-- ── L18 ─────────────────────────────────────────────────────────────────────
(18, 1, 'A1',
 'Membaca akurat frasa panjang dan kalimat pendek berstruktur majemuk sederhana.',
 'Guru berkata: "Baca bagian-bagian ini satu per satu dengan suara jelas."',
 'hasil pengamatan yang ditulis siswa; keputusan bersama setelah diskusi; tanaman tumbuh subur karena dirawat; siswa belajar tekun sehingga nilainya meningkat; warga bekerja sama ketika lingkungan kotor; ibu menyiapkan sarapan sebelum berangkat bekerja',
 'Minimal 5 dari 6 frasa atau kalimat dibaca benar dan tidak terbata panjang.'),
(18, 2, 'B1',
 'Mengevaluasi ketepatan struktur kalimat dan koherensi paragraf dalam teks.',
 'Guru menulis paragraf pendek yang memiliki satu kalimat tidak koheren dan satu struktur kalimat lemah. Anak menunjuk/menyebut bagian bermasalah.',
 '"Siswa kelas besar perlu mengatur waktu belajar. Tugas sekolah biasanya lebih banyak. Karena jadwal membantu tugas tidak menumpuk. Pisang matang berwarna kuning."',
 'Lulus bila anak menemukan 2 masalah utama: kalimat "Karena jadwal..." belum lengkap/kurang tepat strukturnya, dan kalimat "Pisang matang..." tidak koheren dengan paragraf.'),
(18, 3, 'E1',
 'Mengenali bilangan bulat besar dan bentuk baku sederhana serta memperkirakan hasil perhitungan.',
 'Guru berkata: "Bacalah bilangan ini. Lalu pilih perkiraan hasil yang paling masuk akal."',
 'Baca: 1.250.000; 3.600.000. Estimasi: 498 + 503 ≈ ?; 1.980 − 995 ≈ ?; 49 × 21 ≈ ? (pilihan: 100, 1.000, 10.000)',
 '4 dari 5 benar.'),
(18, 4, 'D1',
 'Menulis teks multi-paragraf pendek berdasarkan kerangka terstruktur.',
 'Guru menulis kerangka 3 paragraf: pembuka, isi, penutup. Guru berkata: "Tulis teks pendek tiga paragraf dengan mengikuti kerangka ini."',
 'Kerangka 3 paragraf dengan poin singkat; model tetap terlihat.',
 '3 paragraf jelas; tiap paragraf minimal 2 kalimat; memuat pembuka, isi, penutup; ≤6 kesalahan ejaan per 130 kata; pemisahan paragraf benar.'),
(18, 5, 'C1',
 'Membaca teks yang memuat dua sudut pandang berbeda dan membedakannya.',
 'Guru menulis dua paragraf pendek. Katakan: "Baca teks ini. Setelah membaca, tandai atau sebutkan pendapat pertama dan pendapat kedua."',
 'Paragraf 1: Sebagian siswa senang belajar kelompok. Mereka merasa dapat bertanya kepada teman dan membagi tugas. Belajar kelompok juga membuat tugas terasa lebih ringan. / Paragraf 2: Sebagian siswa lain lebih suka belajar sendiri. Mereka merasa lebih fokus dan dapat mengatur waktu sendiri. Belajar sendiri juga membuat mereka tidak mudah terganggu.',
 'Paling banyak 6 kesalahan kata, dan anak dapat membedakan dua sudut pandang: mendukung belajar kelompok dan lebih suka belajar sendiri, masing-masing dengan satu alasan.'),
(18, 6, 'F1',
 'Mengenal mean, median, dan modus dalam data kecil.',
 'Guru berkata: "Sebutkan mana yang disebut rata-rata, nilai tengah, dan nilai yang paling sering muncul. Lalu tunjukkan pada data ini."',
 'Data: 6, 7, 7, 8, 10. Pertanyaan: (1) modus; (2) median; (3) jumlah semua data; (4) banyak data; (5) makna mean sebagai jumlah dibagi banyak data.',
 '4 dari 5 benar.'),
(18, 7, 'A2',
 'Membaca lancar teks 5–6 kalimat dengan kalimat majemuk dan jeda sesuai tanda baca.',
 'Guru berkata: "Baca teks ini sampai selesai dengan tempo wajar. Perhatikan koma, titik, tanda tanya, dan tanda seru."',
 'Siswa kelas enam menyiapkan pameran karya, karena mereka ingin menunjukkan hasil belajar. Setiap kelompok memilih tema yang berbeda, lalu menyusun bahan di meja masing-masing. Guru berkeliling untuk memeriksa kesiapan kelompok. Mengapa kerja sama penting dalam kegiatan seperti ini? Semua anggota harus berbagi tugas, sehingga pekerjaan selesai tepat waktu. Ayo, tunjukkan hasil terbaik dengan percaya diri!',
 'Maksimal 7 kesalahan kata; jeda tanda baca benar minimal 6 dari 8; minimal 5 dari 6 kalimat dibaca tanpa terbata panjang.'),
(18, 8, 'B2',
 'Menyusun teks argumentasi pendek dengan klaim, argumen pendukung, dan simpulan.',
 'Guru memberi topik: "Apakah siswa kelas besar perlu mengatur waktu belajar?" Anak menyampaikan atau menulis teks pendek.',
 'Topik lisan dari guru; tanpa bahan cetak.',
 'Lulus bila teks memuat klaim, sedikitnya satu argumen pendukung, dan simpulan. Ketiganya harus saling berkaitan.'),
(18, 9, 'E2',
 'Menyelesaikan soal terapan bilangan bulat dan pecahan dalam konteks uang, pengukuran, dan data.',
 'Guru berkata: "Kerjakan soal berikut. Tuliskan operasi dan jawabannya."',
 'Rp50.000 dipakai Rp18.500 dan Rp12.000, sisa?; 3/4 kg gula + 1/4 kg; suhu 4°C turun 9°C; pita 2,5 m dipotong 0,75 m; jumlah data 12, 15, 13, 10',
 '4 dari 5 benar.'),
(18, 10, 'D2',
 'Menulis teks argumentasi pendek dengan klaim, argumen pendukung, dan simpulan berkaitan.',
 'Guru berkata: "Tulis teks argumentasi pendek tentang pendapatmu. Sertakan klaim, beberapa alasan, dan simpulan."',
 'Pensil dan kertas polos; tidak ada model atau kerangka tertulis.',
 '2–3 paragraf, 120–160 kata; ada klaim, minimal 2 argumen pendukung, dan simpulan; simpulan berkaitan dengan klaim; ≤9 kesalahan ejaan per 160 kata; paragraf terpisah jelas.'),
(18, 11, 'C2',
 'Mensintesis informasi dari dua bagian teks yang membahas aspek berbeda dari satu topik.',
 'Setelah anak membaca teks C1 L18, tanyakan: "Apa persamaan dua bagian teks ini?" "Apa perbedaannya?" "Menurut teks, kapan belajar kelompok lebih membantu dan kapan belajar sendiri lebih membantu?"',
 'Teks sama dengan C1 L18.',
 '2 dari 3 tepat. Kunci: persamaan sama-sama cara belajar; perbedaan kelompok dibantu teman, sendiri lebih fokus/atur waktu; sintesis kelompok cocok saat perlu bertanya/berbagi tugas, sendiri cocok saat perlu fokus.'),
(18, 12, 'F2',
 'Menghitung mean, median, dan modus dari data kecil serta menafsirkan hasilnya.',
 'Guru berkata: "Hitung rata-rata, nilai tengah, dan nilai yang paling sering muncul. Lalu jawab satu pertanyaan makna data."',
 'Data 1: 6, 7, 7, 8, 10. Data 2: 12, 14, 15, 15, 19. Pertanyaan: (1) mean Data 1; (2) median Data 1; (3) modus Data 1; (4) mean Data 2; (5) modus Data 2.',
 '4 dari 5 benar.'),
(18, 13, 'EN',
 'Menulis 2–3 kalimat Bahasa Inggris tentang topik bebas dengan ejaan dan tanda baca dasar.',
 'Guru berkata: "Write two or three sentences in English about yourself, your family, your hobby, or your school."',
 'Topik pilihan di papan: myself, my family, my hobby, my school.',
 'Anak menulis minimal 2 kalimat; 2 dari 3 (atau keduanya jika hanya 2) dapat dipahami; kapital awal dan titik akhir benar pada minimal 2 kalimat.'),
(18, 14, 'KR',
 'Kontribusi memberi dampak positif bagi keluarga atau komunitas kecil.',
 'Guru berkata: "Apa kontribusi kecil yang bisa kamu lakukan minggu ini?"',
 '"Di rumah atau kelas ada pekerjaan kecil yang sering tertunda, seperti merapikan buku, membersihkan meja, atau membantu adik belajar."',
 'Respons memenuhi 2 dari 3: menyebut tindakan nyata, menjelaskan manfaat bagi orang lain, realistis dilakukan.');
